{
  "swagger": "2.0",
  "info": {
    "title": "OneNote Consumer",
    "description": "Microsoft OneNote is your digital notebook. One cross-functional notebook for all your notetaking needs.",
    "version": "1.0",
    "contact": {
      "name": "Troy Taylor",
      "url": "https://www.hitachisolutions.com",
      "email": "ttaylor@hitachisolutions.com"
    }
  },
  "host": "graph.microsoft.com",
  "basePath": "/v1.0/me/onenote",
  "schemes": [
    "https"
  ],
  "paths": {
    "/notebooks": {
      "get": {
        "summary": "Get my notebooks",
        "description": "Retrieves my notebooks.",
        "operationId": "NotebookGet"
      },
      "post": {
        "summary": "Create notebook",
        "description": "Creates a new OneNote notebook.",
        "operationId": "NotebookPost"
      }
    },
    "/notebooks/{notebook-id}": {
      "get": {
        "summary": "Get notebook",
        "description": "Retrieves a specific notebook",
        "operationId": "NotebookGetA"
      }
    },
    "/notebooks/{notebook-id}/sections": {
      "get": {
        "summary": "List sections",
        "description": "Retrieves a list of sections from the specified notebook.",
        "operationId": "SectionGet"
      },
      "post": {
        "summary": "Create section",
        "description": "Create a new section in the specified notebook.",
        "operationId": "SectionPost"
      }
    },
    "/sections/{section-id}/pages": {
      "get": {
        "summary": "List pages",
        "description": "Retrieves a list of pages from the specified section",
        "operationId": "PageGet"
      },
      "post": {
        "summary": "Create page",
        "description": "Create a new page in the specified section",
        "operationId": "PagePost"
      }
    }
  },
  "securityDefinitions": {
    "oauth2_auth": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://login.microsoftonline.com/consumers/oauth2/v2.0/authorize",
      "tokenUrl": "https://login.microsoftonline.com/consumers/oauth2/v2.0/token",
      "scopes": {
        "offline_access Notes.Create Notes.Read Notes.ReadWrite Notes.ReadWrite.CreatedByApp": "offline_access Notes.Create Notes.Read Notes.ReadWrite Notes.ReadWrite.CreatedByApp"
      }
    }
  },
  "security": [
    {
      "oauth2_auth": [
        "offline_access Notes.Create Notes.Read Notes.ReadWrite Notes.ReadWrite.CreatedByApp"
      ]
    }
  ],
  "tags": []
}