pr:
  branches:
    include:
    - master
    - releases/*
  paths:
    include:
    - connectors/*

jobs:
- job: validate_pr
  steps:
  - task: NuGetCommand@2
    inputs:
      command: 'custom'
      feedsToUse: 'select'
      versioningScheme: 'off'
      arguments: 'sources Add -Name $(nugetpackagesourcename) -Source $(nugetmanualmirrorurl)'
  - task: NuGetCommand@2
    inputs:
      command: 'custom'
      feedsToUse: 'select'
      versioningScheme: 'off'
      arguments: 'install $(ossvalidatorspkg) -Source $(nugetpackagesourcename) -Version $(ossvalidatorsversion) -OutputDirectory $(ossvalidatorspkg)'
  - powershell: |
      nuget
      Get-PackageSource -ProviderName NuGet
      Install-Package -Name $(ossvalidatorspkg) -MinimumVersion $(ossvalidatorsversion) -MaximumVersion $(ossvalidatorsversion) -Source $(nugetpackagesourcename)
      $SourceRepo = [System.Uri]$Env:SYSTEM_PULLREQUEST_SOURCEREPOSITORYURI
      $SourceRepo = $SourceRepo.AbsolutePath -replace '.git'

      pwd
      ls

      iex "$(ossvalidatorspkg)/$(swaggervalidator)"


      $GitUrl = '$(githubapi)' + $SourceRepo + '/pulls/' + $Env:SYSTEM_PULLREQUEST_PULLREQUESTNUMBER + '/files'

      $Files = Invoke-RestMethod -Uri $GitUrl -Method Get

      ForEach ($File in $Files) {
        $filename = $File.filename
        if($filename.EndsWith('.swagger.json')) {
          iex "$(ossvalidatorspkg)/$(swaggervalidator) $filename"
          Write-Host $Result
        }
      }