pr:
  branches:
    include:
    - master
    - releases/*
  paths:
    include:
    - connectors/*

jobs:
- job: get_content
  steps:
  - powershell: |
      mkdir swgvldtr
      cd swgvldtr
  - task: NuGetCommand@2
    inputs:
      command: 'custom'
      feedsToUse: 'select'
      versioningScheme: 'off'
      arguments: 'sources Add -Name msazure -Source https://msazure.pkgs.visualstudio.com/DefaultCollection/_apis/packaging/ManualMirror/nuget/index.json'
  - task: NuGetCommand@2
    inputs:
      command: 'custom'
      feedsToUse: 'select'
      versioningScheme: 'off'
      arguments: 'install BAPIConnectors.SwaggerValidator -Source msazure'
  - powershell: |
      $GitUrl = 'https://api.github.com/repos'

      $SourceRepo = [System.Uri]$Env:SYSTEM_PULLREQUEST_SOURCEREPOSITORYURI
      $SourceRepo = $SourceRepo.AbsolutePath -replace '.git'
      $GitUrl = $GitUrl + $SourceRepo + '/pulls/' + $Env:SYSTEM_PULLREQUEST_PULLREQUESTNUMBER + '/files'
      $Files = Invoke-RestMethod -Uri $GitUrl -Method Get
      
      $SwaggerUri = 'https://connectorgithubcheck.azurewebsites.net/api/ConnectorGithubCheckRun?code=Ja8rWjlRxfsOo4AhKcQh9Ld5Bhzt3eAvC6n4OHAG6ZHRptBecMVdFQ=='
      ForEach ($File in $Files) {
        $filename = $File.filename
        Write-Host $filename
        if($filename.EndsWith('.swagger.json')) {
          $Form = (Get-Content $filename)
          $Result = Invoke-RestMethod -Uri $SwaggerUri -Method Post -Body $Form
          Write-Host $Result
        }
      }