{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Xero OAuth 2.0",
    "description": "Xero is an accounting solution for small and medium sized businesses.  This connector enables you to access Xero data from the Power Platform.",
    "contact": {
      "name": "Phil Stubbington / Henley Ridge Management Consulting Limited",
      "url": "https://www.henleyridge.co.uk",
      "email": "philstubbington@henleyridge.co.uk"
    }
  },



  "host": "api.xero.com",
  "basePath": "/api.xro/2.0",
  "securityDefinitions": {
    "OAuth2": {
      "type": "oauth2",
      "description": "For more information",
      "flow": "accessCode",
      "authorizationUrl": "https://login.xero.com/identity/connect/authorize",
      "tokenUrl": "https://identity.xero.com/connect/token",
      "scopes": {
        "email": "Grant read-only access to your email",
        "openid": "Grant read-only access to your open id",
        "profile": "your profile information",
        "accounting.attachments": "Grant read-write access to attachments",
        "accounting.attachments.read": "Grant read-only access to attachments",
        "accounting.contacts": "Grant read-write access to contacts and contact groups",
        "accounting.contacts.read": "Grant read-only access to contacts and contact groups",
        "accounting.journals.read": "Grant read-only access to journals",
        "accounting.reports.read": "Grant read-only access to accounting reports",
        "accounting.reports.tenninetynine.read": "Grant read-only access to 1099 reports",
        "accounting.settings": "Grant read-write access to organisation and account settings",
        "accounting.settings.read": "Grant read-only access to organisation and account settings",
        "accounting.transactions": "Grant read-write access to bank transactions, credit notes, invoices, repeating invoices",
        "accounting.transactions.read": "Grant read-only access to invoices",
        "paymentservices": "Grant read-write access to payment services",
        "accounting.budgets.read": ""
      }
    }
  },
  "schemes": [
    "https"
  ],
  "paths": {
    "/Accounts": {
      "get": {
        "description": "Retrieves the full chart of accounts",
        "summary": "getAccounts",
        "tags": [
          "Accounting"
        ],
        "operationId": "getAccounts",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings",
              "accounting.settings.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates a new chart of accounts",
        "summary": "createAccount",
        "tags": [
          "Accounting"
        ],
        "operationId": "createAccount",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings"
            ]
          }
        ]
      }
    },
    "/Accounts/{AccountID}": {
      "get": {
        "description": "Retrieves a single chart of accounts by using a unique account Id",
        "summary": "getAccount",
        "tags": [
          "Accounting"
        ],
        "operationId": "getAccount",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings",
              "accounting.settings.read"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates a chart of accounts",
        "summary": "updateAccount",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateAccount",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings"
            ]
          }
        ]
      },
      "delete": {
        "description": "Deletes a chart of accounts",
        "summary": "deleteAccount",
        "tags": [
          "Accounting"
        ],
        "operationId": "deleteAccount",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings"
            ]
          }
        ]
      }
    },
    "/Accounts/{AccountID}/Attachments": {
      "get": {
        "description": "Retrieves attachments for a specific accounts by using a unique account Id",
        "summary": "getAccountAttachments",
        "tags": [
          "Accounting"
        ],
        "operationId": "getAccountAttachments",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      }
    },
    "/Accounts/{AccountID}/Attachments/{AttachmentID}": {
      "get": {
        "description": "Retrieves a specific attachment from a specific account using a unique attachment Id",
        "summary": "getAccountAttachmentById",
        "tags": [
          "Accounting"
        ],
        "operationId": "getAccountAttachmentById",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      }
    },
    "/Accounts/{AccountID}/Attachments/{FileName}": {
      "get": {
        "description": "Retrieves an attachment for a specific account by filename",
        "summary": "getAccountAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "getAccountAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates attachment on a specific account by filename",
        "summary": "updateAccountAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateAccountAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates an attachment on a specific account",
        "summary": "createAccountAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "createAccountAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments"
            ]
          }
        ]
      }
    }
  },
  "security": [],
  "tags": [
    {
      "name": "Accounting",
      "description": ""
    }
  ]
}