{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Xero OAuth 2.0",
    "description": "Xero is an accounting solution for small and medium sized businesses.  This connector enables you to access Xero data from the Power Platform.",
    "contact": {
      "name": "Phil Stubbington / Henley Ridge Management Consulting Limited",
      "url": "https://www.henleyridge.co.uk",
      "email": "philstubbington@henleyridge.co.uk"
    }
  },



  "host": "api.xero.com",
  "basePath": "/api.xro/2.0",
  "securityDefinitions": {
    "OAuth2": {
      "type": "oauth2",
      "description": "For more information",
      "flow": "accessCode",
      "authorizationUrl": "https://login.xero.com/identity/connect/authorize",
      "tokenUrl": "https://identity.xero.com/connect/token",
      "scopes": {
        "email": "Grant read-only access to your email",
        "openid": "Grant read-only access to your open id",
        "profile": "your profile information",
        "accounting.attachments": "Grant read-write access to attachments",
        "accounting.attachments.read": "Grant read-only access to attachments",
        "accounting.contacts": "Grant read-write access to contacts and contact groups",
        "accounting.contacts.read": "Grant read-only access to contacts and contact groups",
        "accounting.journals.read": "Grant read-only access to journals",
        "accounting.reports.read": "Grant read-only access to accounting reports",
        "accounting.reports.tenninetynine.read": "Grant read-only access to 1099 reports",
        "accounting.settings": "Grant read-write access to organisation and account settings",
        "accounting.settings.read": "Grant read-only access to organisation and account settings",
        "accounting.transactions": "Grant read-write access to bank transactions, credit notes, invoices, repeating invoices",
        "accounting.transactions.read": "Grant read-only access to invoices",
        "paymentservices": "Grant read-write access to payment services",
        "accounting.budgets.read": ""
      }
    }
  },
  "schemes": [
    "https"
  ],
  "paths": {
    "/Accounts": {
      "get": {
        "description": "Retrieves the full chart of accounts",
        "summary": "getAccounts",
        "tags": [
          "Accounting"
        ],
        "operationId": "getAccounts",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings",
              "accounting.settings.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates a new chart of accounts",
        "summary": "createAccount",
        "tags": [
          "Accounting"
        ],
        "operationId": "createAccount",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings"
            ]
          }
        ]
      }
    },
    "/Accounts/{AccountID}": {
      "get": {
        "description": "Retrieves a single chart of accounts by using a unique account Id",
        "summary": "getAccount",
        "tags": [
          "Accounting"
        ],
        "operationId": "getAccount",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings",
              "accounting.settings.read"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates a chart of accounts",
        "summary": "updateAccount",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateAccount",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings"
            ]
          }
        ]
      },
      "delete": {
        "description": "Deletes a chart of accounts",
        "summary": "deleteAccount",
        "tags": [
          "Accounting"
        ],
        "operationId": "deleteAccount",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings"
            ]
          }
        ]
      }
    },
    "/Accounts/{AccountID}/Attachments": {
      "get": {
        "description": "Retrieves attachments for a specific accounts by using a unique account Id",
        "summary": "getAccountAttachments",
        "tags": [
          "Accounting"
        ],
        "operationId": "getAccountAttachments",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      }
    },
    "/Accounts/{AccountID}/Attachments/{AttachmentID}": {
      "get": {
        "description": "Retrieves a specific attachment from a specific account using a unique attachment Id",
        "summary": "getAccountAttachmentById",
        "tags": [
          "Accounting"
        ],
        "operationId": "getAccountAttachmentById",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      }
    },
    "/Accounts/{AccountID}/Attachments/{FileName}": {
      "get": {
        "description": "Retrieves an attachment for a specific account by filename",
        "summary": "getAccountAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "getAccountAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates attachment on a specific account by filename",
        "summary": "updateAccountAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateAccountAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates an attachment on a specific account",
        "summary": "createAccountAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "createAccountAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments"
            ]
          }
        ]
      }
    },
    "/BatchPayments": {
      "get": {
        "description": "Retrieves either one or many batch payments for invoices",
        "summary": "getBatchPayments",
        "tags": [
          "Accounting"
        ],
        "operationId": "getBatchPayments",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates one or many batch payments for invoices",
        "summary": "createBatchPayment",
        "tags": [
          "Accounting"
        ],
        "operationId": "createBatchPayment",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/BatchPayments/{BatchPaymentID}/History": {
      "get": {
        "description": "Retrieves history from a specific batch payment",
        "summary": "getBatchPaymentHistory",
        "tags": [
          "Accounting"
        ],
        "operationId": "getBatchPaymentHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates a history record for a specific batch payment",
        "summary": "createBatchPaymentHistoryRecord",
        "tags": [
          "Accounting"
        ],
        "operationId": "createBatchPaymentHistoryRecord",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/BankTransactions": {
      "get": {
        "description": "Retrieves any spent or received money transactions",
        "summary": "getBankTransactions",
        "tags": [
          "Accounting"
        ],
        "operationId": "getBankTransactions",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates one or more spent or received money transaction",
        "summary": "createBankTransactions",
        "tags": [
          "Accounting"
        ],
        "operationId": "createBankTransactions",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates or creates one or more spent or received money transaction",
        "summary": "updateOrCreateBankTransactions",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateOrCreateBankTransactions",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/BankTransactions/{BankTransactionID}": {
      "get": {
        "description": "Retrieves a single spent or received money transaction by using a unique bank transaction Id",
        "summary": "getBankTransaction",
        "tags": [
          "Accounting"
        ],
        "operationId": "getBankTransaction",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates a single spent or received money transaction",
        "summary": "updateBankTransaction",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateBankTransaction",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/BankTransactions/{BankTransactionID}/Attachments": {
      "get": {
        "description": "Retrieves any attachments from a specific bank transactions",
        "summary": "getBankTransactionAttachments",
        "tags": [
          "Accounting"
        ],
        "operationId": "getBankTransactionAttachments",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      }
    },
    "/BankTransactions/{BankTransactionID}/Attachments/{AttachmentID}": {
      "get": {
        "description": "Retrieves specific attachments from a specific BankTransaction using a unique attachment Id",
        "summary": "getBankTransactionAttachmentById",
        "tags": [
          "Accounting"
        ],
        "operationId": "getBankTransactionAttachmentById",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      }
    },
    "/BankTransactions/{BankTransactionID}/Attachments/{FileName}": {
      "get": {
        "description": "Retrieves a specific attachment from a specific bank transaction by filename",
        "summary": "getBankTransactionAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "getBankTransactionAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates a specific attachment from a specific bank transaction by filename",
        "summary": "updateBankTransactionAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateBankTransactionAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates an attachment for a specific bank transaction by filename",
        "summary": "createBankTransactionAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "createBankTransactionAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments"
            ]
          }
        ]
      }
    },
    "/BankTransactions/{BankTransactionID}/History": {
      "get": {
        "description": "Retrieves history from a specific bank transaction using a unique bank transaction Id",
        "summary": "getBankTransactionsHistory",
        "tags": [
          "Accounting"
        ],
        "operationId": "getBankTransactionsHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates a history record for a specific bank transactions",
        "summary": "createBankTransactionHistoryRecord",
        "tags": [
          "Accounting"
        ],
        "operationId": "createBankTransactionHistoryRecord",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/BankTransfers": {
      "get": {
        "description": "Retrieves all bank transfers",
        "summary": "getBankTransfers",
        "tags": [
          "Accounting"
        ],
        "operationId": "getBankTransfers",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates a bank transfer",
        "summary": "createBankTransfer",
        "tags": [
          "Accounting"
        ],
        "operationId": "createBankTransfer",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/BankTransfers/{BankTransferID}": {
      "get": {
        "description": "Retrieves specific bank transfers by using a unique bank transfer Id",
        "summary": "getBankTransfer",
        "tags": [
          "Accounting"
        ],
        "operationId": "getBankTransfer",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      }
    },
    "/BankTransfers/{BankTransferID}/Attachments": {
      "get": {
        "description": "Retrieves attachments from a specific bank transfer",
        "summary": "getBankTransferAttachments",
        "tags": [
          "Accounting"
        ],
        "operationId": "getBankTransferAttachments",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      }
    },
    "/BankTransfers/{BankTransferID}/Attachments/{AttachmentID}": {
      "get": {
        "description": "Retrieves a specific attachment from a specific bank transfer using a unique attachment ID",
        "summary": "getBankTransferAttachmentById",
        "tags": [
          "Accounting"
        ],
        "operationId": "getBankTransferAttachmentById",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      }
    },
    "/BankTransfers/{BankTransferID}/Attachments/{FileName}": {
      "get": {
        "description": "Retrieves a specific attachment on a specific bank transfer by file name",
        "summary": "getBankTransferAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "getBankTransferAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      },
      "post": {
        "description": "",
        "summary": "updateBankTransferAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateBankTransferAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments"
            ]
          }
        ]
      },
      "put": {
        "description": "",
        "summary": "createBankTransferAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "createBankTransferAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments"
            ]
          }
        ]
      }
    },
    "/BankTransfers/{BankTransferID}/History": {
      "get": {
        "description": "Retrieves history from a specific bank transfer using a unique bank transfer Id",
        "summary": "getBankTransferHistory",
        "tags": [
          "Accounting"
        ],
        "operationId": "getBankTransferHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates a history record for a specific bank transfer",
        "summary": "createBankTransferHistoryRecord",
        "tags": [
          "Accounting"
        ],
        "operationId": "createBankTransferHistoryRecord",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/BrandingThemes": {
      "get": {
        "description": "Retrieves all the branding themes",
        "summary": "getBrandingThemes",
        "tags": [
          "Accounting"
        ],
        "operationId": "getBrandingThemes",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings",
              "accounting.settings.read"
            ]
          }
        ]
      }
    },
    "/BrandingThemes/{BrandingThemeID}": {
      "get": {
        "description": "Retrieves a specific branding theme using a unique branding theme Id",
        "summary": "getBrandingTheme",
        "tags": [
          "Accounting"
        ],
        "operationId": "getBrandingTheme",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings",
              "accounting.settings.read"
            ]
          }
        ]
      }
    },
    "/BrandingThemes/{BrandingThemeID}/PaymentServices": {
      "get": {
        "description": "Retrieves the payment services for a specific branding theme",
        "summary": "getBrandingThemePaymentServices",
        "tags": [
          "Accounting"
        ],
        "operationId": "getBrandingThemePaymentServices",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "paymentservices"
            ]
          }
        ]
      },
      "post": {
        "description": "Creates a new custom payment service for a specific branding theme",
        "summary": "createBrandingThemePaymentServices",
        "tags": [
          "Accounting"
        ],
        "operationId": "createBrandingThemePaymentServices",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "paymentservices"
            ]
          }
        ]
      }
    },
    "/Budgets": {
      "get": {
        "description": "Retrieve a list of budgets",
        "summary": "getBudgets",
        "tags": [
          "Accounting"
        ],
        "operationId": "getBudgets",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.budgets.read"
            ]
          }
        ]
      }
    },
    "/Budgets/{BudgetID}": {
      "get": {
        "description": "Retrieves a specific budget, which includes budget lines",
        "summary": "getBudget",
        "tags": [
          "Accounting"
        ],
        "operationId": "getBudget",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.budgets.read"
            ]
          }
        ]
      }
    },
    "/Contacts": {
      "get": {
        "description": "Retrieves all contacts in a Xero organisation",
        "summary": "getContacts",
        "tags": [
          "Accounting"
        ],
        "operationId": "getContacts",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.contacts",
              "accounting.contacts.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates multiple contacts (bulk) in a Xero organisation",
        "summary": "createContacts",
        "tags": [
          "Accounting"
        ],
        "operationId": "createContacts",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.contacts"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates or creates one or more contacts in a Xero organisation",
        "summary": "updateOrCreateContacts",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateOrCreateContacts",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.contacts"
            ]
          }
        ]
      }
    },
    "/Contacts/{ContactNumber}": {
      "get": {
        "description": "Retrieves a specific contact by contact number in a Xero organisation",
        "summary": "getContactByContactNumber",
        "tags": [
          "Accounting"
        ],
        "operationId": "getContactByContactNumber",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.contacts",
              "accounting.contacts.read"
            ]
          }
        ]
      }
    },
    "/Contacts/{ContactID}": {
      "get": {
        "description": "Retrieves a specific contacts in a Xero organisation using a unique contact Id",
        "summary": "getContact",
        "tags": [
          "Accounting"
        ],
        "operationId": "getContact",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.contacts",
              "accounting.contacts.read"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates a specific contact in a Xero organisation",
        "summary": "updateContact",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateContact",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.contacts"
            ]
          }
        ]
      }
    },
    "/Contacts/{ContactID}/Attachments": {
      "get": {
        "description": "Retrieves attachments for a specific contact in a Xero organisation",
        "summary": "getContactAttachments",
        "tags": [
          "Accounting"
        ],
        "operationId": "getContactAttachments",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      }
    },
    "/Contacts/{ContactID}/Attachments/{AttachmentID}": {
      "get": {
        "description": "Retrieves a specific attachment from a specific contact using a unique attachment Id",
        "summary": "getContactAttachmentById",
        "tags": [
          "Accounting"
        ],
        "operationId": "getContactAttachmentById",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      }
    },
    "/Contacts/{ContactID}/Attachments/{FileName}": {
      "get": {
        "description": "Retrieves a specific attachment from a specific contact by file name",
        "summary": "getContactAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "getContactAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      },
      "post": {
        "description": "",
        "summary": "updateContactAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateContactAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments"
            ]
          }
        ]
      },
      "put": {
        "description": "",
        "summary": "createContactAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "createContactAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments"
            ]
          }
        ]
      }
    },
    "/Contacts/{ContactID}/CISSettings": {
      "get": {
        "description": "Retrieves CIS settings for a specific contact in a Xero organisation",
        "summary": "getContactCISSettings",
        "tags": [
          "Accounting"
        ],
        "operationId": "getContactCISSettings",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings",
              "accounting.settings.read"
            ]
          }
        ]
      }
    },
    "/Contacts/{ContactID}/History": {
      "get": {
        "description": "Retrieves history records for a specific contact",
        "summary": "getContactHistory",
        "tags": [
          "Accounting"
        ],
        "operationId": "getContactHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.contacts",
              "accounting.contacts.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates a new history record for a specific contact",
        "summary": "createContactHistory",
        "tags": [
          "Accounting"
        ],
        "operationId": "createContactHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.contacts"
            ]
          }
        ]
      }
    },
    "/ContactGroups": {
      "get": {
        "description": "Retrieves the contact Id and name of each contact group",
        "summary": "getContactGroups",
        "tags": [
          "Accounting"
        ],
        "operationId": "getContactGroups",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.contacts",
              "accounting.contacts.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates a contact group",
        "summary": "createContactGroup",
        "tags": [
          "Accounting"
        ],
        "operationId": "createContactGroup",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.contacts"
            ]
          }
        ]
      }
    },
    "/ContactGroups/{ContactGroupID}": {
      "get": {
        "description": "Retrieves a specific contact group by using a unique contact group Id",
        "summary": "getContactGroup",
        "tags": [
          "Accounting"
        ],
        "operationId": "getContactGroup",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.contacts",
              "accounting.contacts.read"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates a specific contact group",
        "summary": "updateContactGroup",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateContactGroup",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.contacts"
            ]
          }
        ]
      }
    },
    "/ContactGroups/{ContactGroupID}/Contacts": {
      "put": {
        "description": "Creates contacts to a specific contact group",
        "summary": "createContactGroupContacts",
        "tags": [
          "Accounting"
        ],
        "operationId": "createContactGroupContacts",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.contacts"
            ]
          }
        ]
      },
      "delete": {
        "description": "Deletes all contacts from a specific contact group",
        "summary": "deleteContactGroupContacts",
        "tags": [
          "Accounting"
        ],
        "operationId": "deleteContactGroupContacts",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.contacts"
            ]
          }
        ]
      }
    },
    "/ContactGroups/{ContactGroupID}/Contacts/{ContactID}": {
      "delete": {
        "description": "Deletes a specific contact from a contact group using a unique contact Id",
        "summary": "deleteContactGroupContact",
        "tags": [
          "Accounting"
        ],
        "operationId": "deleteContactGroupContact",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.contacts"
            ]
          }
        ]
      }
    },
    "/CreditNotes": {
      "get": {
        "description": "Retrieves any credit notes",
        "summary": "getCreditNotes",
        "tags": [
          "Accounting"
        ],
        "operationId": "getCreditNotes",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates a new credit note",
        "summary": "createCreditNotes",
        "tags": [
          "Accounting"
        ],
        "operationId": "createCreditNotes",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates or creates one or more credit notes",
        "summary": "updateOrCreateCreditNotes",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateOrCreateCreditNotes",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/CreditNotes/{CreditNoteID}": {
      "get": {
        "description": "Retrieves a specific credit note using a unique credit note Id",
        "summary": "getCreditNote",
        "tags": [
          "Accounting"
        ],
        "operationId": "getCreditNote",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates a specific credit note",
        "summary": "updateCreditNote",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateCreditNote",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/CreditNotes/{CreditNoteID}/Attachments": {
      "get": {
        "description": "Retrieves attachments for a specific credit notes",
        "summary": "getCreditNoteAttachments",
        "tags": [
          "Accounting"
        ],
        "operationId": "getCreditNoteAttachments",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      }
    },
    "/CreditNotes/{CreditNoteID}/Attachments/{AttachmentID}": {
      "get": {
        "description": "Retrieves a specific attachment from a specific credit note using a unique attachment Id",
        "summary": "getCreditNoteAttachmentById",
        "tags": [
          "Accounting"
        ],
        "operationId": "getCreditNoteAttachmentById",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      }
    },
    "/CreditNotes/{CreditNoteID}/Attachments/{FileName}": {
      "get": {
        "description": "Retrieves a specific attachment on a specific credit note by file name",
        "summary": "getCreditNoteAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "getCreditNoteAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates attachments on a specific credit note by file name",
        "summary": "updateCreditNoteAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateCreditNoteAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates an attachment for a specific credit note",
        "summary": "createCreditNoteAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "createCreditNoteAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments"
            ]
          }
        ]
      }
    },
    "/CreditNotes/{CreditNoteID}/pdf": {
      "get": {
        "description": "Retrieves credit notes as PDF files",
        "summary": "getCreditNoteAsPdf",
        "tags": [
          "Accounting"
        ],
        "operationId": "getCreditNoteAsPdf",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      }
    },
    "/CreditNotes/{CreditNoteID}/Allocations": {
      "put": {
        "description": "Creates allocation for a specific credit note",
        "summary": "createCreditNoteAllocation",
        "tags": [
          "Accounting"
        ],
        "operationId": "createCreditNoteAllocation",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/CreditNotes/{CreditNoteID}/History": {
      "get": {
        "description": "Retrieves history records of a specific credit note",
        "summary": "getCreditNoteHistory",
        "tags": [
          "Accounting"
        ],
        "operationId": "getCreditNoteHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Retrieves history records of a specific credit note",
        "summary": "createCreditNoteHistory",
        "tags": [
          "Accounting"
        ],
        "operationId": "createCreditNoteHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/Currencies": {
      "get": {
        "description": "Retrieves currencies for your Xero organisation",
        "summary": "getCurrencies",
        "tags": [
          "Accounting"
        ],
        "operationId": "getCurrencies",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings",
              "accounting.settings.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Create a new currency for a Xero organisation",
        "summary": "createCurrency",
        "tags": [
          "Accounting"
        ],
        "operationId": "createCurrency",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings"
            ]
          }
        ]
      }
    },
    "/Employees": {
      "get": {
        "description": "Retrieves employees used in Xero payrun",
        "summary": "getEmployees",
        "tags": [
          "Accounting"
        ],
        "operationId": "getEmployees",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings",
              "accounting.settings.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates new employees used in Xero payrun",
        "summary": "createEmployees",
        "tags": [
          "Accounting"
        ],
        "operationId": "createEmployees",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings"
            ]
          }
        ]
      },
      "post": {
        "description": "Creates a single new employees used in Xero payrun",
        "summary": "updateOrCreateEmployees",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateOrCreateEmployees",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings"
            ]
          }
        ]
      }
    },
    "/Employees/{EmployeeID}": {
      "get": {
        "description": "Retrieves a specific employee used in Xero payrun using a unique employee Id",
        "summary": "getEmployee",
        "tags": [
          "Accounting"
        ],
        "operationId": "getEmployee",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings",
              "accounting.settings.read"
            ]
          }
        ]
      }
    },
    "/ExpenseClaims": {
      "get": {
        "description": "Retrieves expense claims",
        "summary": "getExpenseClaims",
        "tags": [
          "Accounting"
        ],
        "operationId": "getExpenseClaims",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates expense claims",
        "summary": "createExpenseClaims",
        "tags": [
          "Accounting"
        ],
        "operationId": "createExpenseClaims",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/ExpenseClaims/{ExpenseClaimID}": {
      "get": {
        "description": "Retrieves a specific expense claim using a unique expense claim Id",
        "summary": "getExpenseClaim",
        "tags": [
          "Accounting"
        ],
        "operationId": "getExpenseClaim",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates a specific expense claims",
        "summary": "updateExpenseClaim",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateExpenseClaim",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/ExpenseClaims/{ExpenseClaimID}/History": {
      "get": {
        "description": "Retrieves history records of a specific expense claim",
        "summary": "getExpenseClaimHistory",
        "tags": [
          "Accounting"
        ],
        "operationId": "getExpenseClaimHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates a history record for a specific expense claim",
        "summary": "createExpenseClaimHistory",
        "tags": [
          "Accounting"
        ],
        "operationId": "createExpenseClaimHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/Invoices": {
      "get": {
        "description": "Retrieves sales invoices or purchase bills",
        "summary": "getInvoices",
        "tags": [
          "Accounting"
        ],
        "operationId": "getInvoices",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates one or more sales invoices or purchase bills",
        "summary": "createInvoices",
        "tags": [
          "Accounting"
        ],
        "operationId": "createInvoices",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates or creates one or more sales invoices or purchase bills",
        "summary": "updateOrCreateInvoices",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateOrCreateInvoices",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/Invoices/{InvoiceID}": {
      "get": {
        "description": "Retrieves a specific sales invoice or purchase bill using a unique invoice Id",
        "summary": "getInvoice",
        "tags": [
          "Accounting"
        ],
        "operationId": "getInvoice",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates a specific sales invoices or purchase bills",
        "summary": "updateInvoice",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateInvoice",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/Invoices/{InvoiceID}/pdf": {
      "get": {
        "description": "Retrieves invoices or purchase bills as PDF files",
        "summary": "getInvoiceAsPdf",
        "tags": [
          "Accounting"
        ],
        "operationId": "getInvoiceAsPdf",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      }
    },
    "/Invoices/{InvoiceID}/Attachments": {
      "get": {
        "description": "Retrieves attachments for a specific invoice or purchase bill",
        "summary": "getInvoiceAttachments",
        "tags": [
          "Accounting"
        ],
        "operationId": "getInvoiceAttachments",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      }
    },
    "/Invoices/{InvoiceID}/Attachments/{AttachmentID}": {
      "get": {
        "description": "Retrieves a specific attachment from a specific invoices or purchase bills by using a unique attachment Id",
        "summary": "getInvoiceAttachmentById",
        "tags": [
          "Accounting"
        ],
        "operationId": "getInvoiceAttachmentById",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      }
    },
    "/Invoices/{InvoiceID}/Attachments/{FileName}": {
      "get": {
        "description": "Retrieves an attachment from a specific invoice or purchase bill by filename",
        "summary": "getInvoiceAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "getInvoiceAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates an attachment from a specific invoices or purchase bill by filename",
        "summary": "updateInvoiceAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateInvoiceAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates an attachment for a specific invoice or purchase bill by filename",
        "summary": "createInvoiceAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "createInvoiceAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments"
            ]
          }
        ]
      }
    },
    "/Invoices/{InvoiceID}/OnlineInvoice": {
      "get": {
        "description": "Retrieves a URL to an online invoice",
        "summary": "getOnlineInvoice",
        "tags": [
          "Accounting"
        ],
        "operationId": "getOnlineInvoice",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      }
    },
    "/Invoices/{InvoiceID}/Email": {
      "post": {
        "description": "Sends a copy of a specific invoice to related contact via email",
        "summary": "emailInvoice",
        "tags": [
          "Accounting"
        ],
        "operationId": "emailInvoice",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/Invoices/{InvoiceID}/History": {
      "get": {
        "description": "Retrieves history records for a specific invoice",
        "summary": "getInvoiceHistory",
        "tags": [
          "Accounting"
        ],
        "operationId": "getInvoiceHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates a history record for a specific invoice",
        "summary": "createInvoiceHistory",
        "tags": [
          "Accounting"
        ],
        "operationId": "createInvoiceHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/InvoiceReminders/Settings": {
      "get": {
        "description": "Retrieves invoice reminder settings",
        "summary": "getInvoiceReminders",
        "tags": [
          "Accounting"
        ],
        "operationId": "getInvoiceReminders",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings",
              "accounting.settings.read"
            ]
          }
        ]
      }
    },
    "/Items": {
      "get": {
        "description": "Retrieves items",
        "summary": "getItems",
        "tags": [
          "Accounting"
        ],
        "operationId": "getItems",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings",
              "accounting.settings.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates one or more items",
        "summary": "createItems",
        "tags": [
          "Accounting"
        ],
        "operationId": "createItems",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates or creates one or more items",
        "summary": "updateOrCreateItems",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateOrCreateItems",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings"
            ]
          }
        ]
      }
    },
    "/Items/{ItemID}": {
      "get": {
        "description": "Retrieves a specific item using a unique item Id",
        "summary": "getItem",
        "tags": [
          "Accounting"
        ],
        "operationId": "getItem",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings",
              "accounting.settings.read"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates a specific item",
        "summary": "updateItem",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateItem",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings"
            ]
          }
        ]
      },
      "delete": {
        "description": "Deletes a specific item",
        "summary": "deleteItem",
        "tags": [
          "Accounting"
        ],
        "operationId": "deleteItem",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings"
            ]
          }
        ]
      }
    },
    "/Items/{ItemID}/History": {
      "get": {
        "description": "Retrieves history for a specific item",
        "summary": "getItemHistory",
        "tags": [
          "Accounting"
        ],
        "operationId": "getItemHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings",
              "accounting.settings.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates a history record for a specific item",
        "summary": "createItemHistory",
        "tags": [
          "Accounting"
        ],
        "operationId": "createItemHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings"
            ]
          }
        ]
      }
    },
    "/Journals": {
      "get": {
        "description": "Retrieves journals",
        "summary": "getJournals",
        "tags": [
          "Accounting"
        ],
        "operationId": "getJournals",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.journals.read"
            ]
          }
        ]
      }
    },
    "/Journals/{JournalID}": {
      "get": {
        "description": "Retrieves a specific journal using a unique journal Id.",
        "summary": "getJournal",
        "tags": [
          "Accounting"
        ],
        "operationId": "getJournal",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.journals.read"
            ]
          }
        ]
      }
    },
    "/Journals/{JournalNumber}": {
      "get": {
        "description": "Retrieves a specific journal using a unique journal number.",
        "summary": "getJournalByNumber",
        "tags": [
          "Accounting"
        ],
        "operationId": "getJournalByNumber",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.journals.read"
            ]
          }
        ]
      }
    },
    "/LinkedTransactions": {
      "get": {
        "description": "Retrieves linked transactions (billable expenses)",
        "summary": "getLinkedTransactions",
        "tags": [
          "Accounting"
        ],
        "operationId": "getLinkedTransactions",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates linked transactions (billable expenses)",
        "summary": "createLinkedTransaction",
        "tags": [
          "Accounting"
        ],
        "operationId": "createLinkedTransaction",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/LinkedTransactions/{LinkedTransactionID}": {
      "get": {
        "description": "Retrieves a specific linked transaction (billable expenses) using a unique linked transaction Id",
        "summary": "getLinkedTransaction",
        "tags": [
          "Accounting"
        ],
        "operationId": "getLinkedTransaction",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates a specific linked transactions (billable expenses)",
        "summary": "updateLinkedTransaction",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateLinkedTransaction",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      },
      "delete": {
        "description": "Deletes a specific linked transactions (billable expenses)",
        "summary": "deleteLinkedTransaction",
        "tags": [
          "Accounting"
        ],
        "operationId": "deleteLinkedTransaction",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/ManualJournals": {
      "get": {
        "description": "Retrieves manual journals",
        "summary": "getManualJournals",
        "tags": [
          "Accounting"
        ],
        "operationId": "getManualJournals",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates one or more manual journals",
        "summary": "createManualJournals",
        "tags": [
          "Accounting"
        ],
        "operationId": "createManualJournals",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates or creates a single manual journal",
        "summary": "updateOrCreateManualJournals",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateOrCreateManualJournals",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/ManualJournals/{ManualJournalID}": {
      "get": {
        "description": "Retrieves a specific manual journal",
        "summary": "getManualJournal",
        "tags": [
          "Accounting"
        ],
        "operationId": "getManualJournal",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates a specific manual journal",
        "summary": "updateManualJournal",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateManualJournal",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/ManualJournals/{ManualJournalID}/Attachments": {
      "get": {
        "description": "Retrieves attachment for a specific manual journal",
        "summary": "getManualJournalAttachments",
        "tags": [
          "Accounting"
        ],
        "operationId": "getManualJournalAttachments",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      }
    },
    "/ManualJournals/{ManualJournalID}/Attachments/{AttachmentID}": {
      "get": {
        "description": "Allows you to retrieve a specific attachment from a specific manual journal using a unique attachment Id",
        "summary": "getManualJournalAttachmentById",
        "tags": [
          "Accounting"
        ],
        "operationId": "getManualJournalAttachmentById",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      }
    },
    "/ManualJournals/{ManualJournalID}/Attachments/{FileName}": {
      "get": {
        "description": "Retrieves a specific attachment from a specific manual journal by file name",
        "summary": "getManualJournalAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "getManualJournalAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates a specific attachment from a specific manual journal by file name",
        "summary": "updateManualJournalAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateManualJournalAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates a specific attachment for a specific manual journal by file name",
        "summary": "createManualJournalAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "createManualJournalAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments"
            ]
          }
        ]
      }
    },
    "/ManualJournals/{ManualJournalID}/History": {
      "get": {
        "description": "Retrieves history for a specific manual journal",
        "summary": "getManualJournalsHistory",
        "tags": [
          "Accounting"
        ],
        "operationId": "getManualJournalsHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates a history record for a specific manual journal",
        "summary": "createManualJournalHistoryRecord",
        "tags": [
          "Accounting"
        ],
        "operationId": "createManualJournalHistoryRecord",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/Organisation": {
      "get": {
        "description": "Retrieves Xero organisation details",
        "summary": "getOrganisations",
        "tags": [
          "Accounting"
        ],
        "operationId": "getOrganisations",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings",
              "accounting.settings.read"
            ]
          }
        ]
      }
    },
    "/Organisation/Actions": {
      "get": {
        "description": "Retrieves a list of the key actions your app has permission to perform in the connected Xero organisation.",
        "summary": "getOrganisationActions",
        "tags": [
          "Accounting"
        ],
        "operationId": "getOrganisationActions",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings",
              "accounting.settings.read"
            ]
          }
        ]
      }
    },
    "/Organisation/{OrganisationID}/CISSettings": {
      "get": {
        "description": "Retrieves the CIS settings for the Xero organistaion.",
        "summary": "getOrganisationCISSettings",
        "tags": [
          "Accounting"
        ],
        "operationId": "getOrganisationCISSettings",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings",
              "accounting.settings.read"
            ]
          }
        ]
      }
    },
    "/Overpayments": {
      "get": {
        "description": "Retrieves overpayments",
        "summary": "getOverpayments",
        "tags": [
          "Accounting"
        ],
        "operationId": "getOverpayments",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      }
    },
    "/Overpayments/{OverpaymentID}": {
      "get": {
        "description": "Retrieves a specific overpayment using a unique overpayment Id",
        "summary": "getOverpayment",
        "tags": [
          "Accounting"
        ],
        "operationId": "getOverpayment",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      }
    },
    "/Overpayments/{OverpaymentID}/Allocations": {
      "put": {
        "description": "Creates a single allocation for a specific overpayment",
        "summary": "createOverpaymentAllocations",
        "tags": [
          "Accounting"
        ],
        "operationId": "createOverpaymentAllocations",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/Overpayments/{OverpaymentID}/History": {
      "get": {
        "description": "Retrieves history records of a specific overpayment",
        "summary": "getOverpaymentHistory",
        "tags": [
          "Accounting"
        ],
        "operationId": "getOverpaymentHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates a history record for a specific overpayment",
        "summary": "createOverpaymentHistory",
        "tags": [
          "Accounting"
        ],
        "operationId": "createOverpaymentHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/Payments": {
      "get": {
        "description": "Retrieves payments for invoices and credit notes",
        "summary": "getPayments",
        "tags": [
          "Accounting"
        ],
        "operationId": "getPayments",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates multiple payments for invoices or credit notes",
        "summary": "createPayments",
        "tags": [
          "Accounting"
        ],
        "operationId": "createPayments",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      },
      "post": {
        "description": "Creates a single payment for invoice or credit notes",
        "summary": "createPayment",
        "tags": [
          "Accounting"
        ],
        "operationId": "createPayment",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/Payments/{PaymentID}": {
      "get": {
        "description": "Retrieves a specific payment for invoices and credit notes using a unique payment Id",
        "summary": "getPayment",
        "tags": [
          "Accounting"
        ],
        "operationId": "getPayment",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates a specific payment for invoices and credit notes",
        "summary": "deletePayment",
        "tags": [
          "Accounting"
        ],
        "operationId": "deletePayment",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/Payments/{PaymentID}/History": {
      "get": {
        "description": "Retrieves history records of a specific payment",
        "summary": "getPaymentHistory",
        "tags": [
          "Accounting"
        ],
        "operationId": "getPaymentHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates a history record for a specific payment",
        "summary": "createPaymentHistory",
        "tags": [
          "Accounting"
        ],
        "operationId": "createPaymentHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/PaymentServices": {
      "get": {
        "description": "Retrieves payment services",
        "summary": "getPaymentServices",
        "tags": [
          "Accounting"
        ],
        "operationId": "getPaymentServices",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "paymentservices"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates a payment service",
        "summary": "createPaymentService",
        "tags": [
          "Accounting"
        ],
        "operationId": "createPaymentService",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "paymentservices"
            ]
          }
        ]
      }
    },
    "/Prepayments": {
      "get": {
        "description": "Retrieves prepayments",
        "summary": "getPrepayments",
        "tags": [
          "Accounting"
        ],
        "operationId": "getPrepayments",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      }
    },
    "/Prepayments/{PrepaymentID}": {
      "get": {
        "description": "Allows you to retrieve a specified prepayments",
        "summary": "getPrepayment",
        "tags": [
          "Accounting"
        ],
        "operationId": "getPrepayment",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      }
    },
    "/Prepayments/{PrepaymentID}/Allocations": {
      "put": {
        "description": "Allows you to create an Allocation for prepayments",
        "summary": "createPrepaymentAllocations",
        "tags": [
          "Accounting"
        ],
        "operationId": "createPrepaymentAllocations",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/Prepayments/{PrepaymentID}/History": {
      "get": {
        "description": "Retrieves history record for a specific prepayment",
        "summary": "getPrepaymentHistory",
        "tags": [
          "Accounting"
        ],
        "operationId": "getPrepaymentHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates a history record for a specific prepayment",
        "summary": "createPrepaymentHistory",
        "tags": [
          "Accounting"
        ],
        "operationId": "createPrepaymentHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/PurchaseOrders": {
      "get": {
        "description": "Retrieves purchase orders",
        "summary": "getPurchaseOrders",
        "tags": [
          "Accounting"
        ],
        "operationId": "getPurchaseOrders",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates one or more purchase orders",
        "summary": "createPurchaseOrders",
        "tags": [
          "Accounting"
        ],
        "operationId": "createPurchaseOrders",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates or creates one or more purchase orders",
        "summary": "updateOrCreatePurchaseOrders",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateOrCreatePurchaseOrders",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/PurchaseOrders/{PurchaseOrderID}/pdf": {
      "get": {
        "description": "Retrieves specific purchase order as PDF files using a unique purchase order Id",
        "summary": "getPurchaseOrderAsPdf",
        "tags": [
          "Accounting"
        ],
        "operationId": "getPurchaseOrderAsPdf",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      }
    },
    "/PurchaseOrders/{PurchaseOrderID}": {
      "get": {
        "description": "Retrieves a specific purchase order using a unique purchase order Id",
        "summary": "getPurchaseOrder",
        "tags": [
          "Accounting"
        ],
        "operationId": "getPurchaseOrder",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates a specific purchase order",
        "summary": "updatePurchaseOrder",
        "tags": [
          "Accounting"
        ],
        "operationId": "updatePurchaseOrder",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/PurchaseOrders/{PurchaseOrderNumber}": {
      "get": {
        "description": "Retrieves a specific purchase order using purchase order number",
        "summary": "getPurchaseOrderByNumber",
        "tags": [
          "Accounting"
        ],
        "operationId": "getPurchaseOrderByNumber",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      }
    },
    "/PurchaseOrders/{PurchaseOrderID}/History": {
      "get": {
        "description": "Retrieves history for a specific purchase order",
        "summary": "getPurchaseOrderHistory",
        "tags": [
          "Accounting"
        ],
        "operationId": "getPurchaseOrderHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates a history record for a specific purchase orders",
        "summary": "createPurchaseOrderHistory",
        "tags": [
          "Accounting"
        ],
        "operationId": "createPurchaseOrderHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/PurchaseOrders/{PurchaseOrderID}/Attachments": {
      "get": {
        "description": "Retrieves attachments for a specific purchase order",
        "summary": "getPurchaseOrderAttachments",
        "tags": [
          "Accounting"
        ],
        "operationId": "getPurchaseOrderAttachments",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      }
    },
    "/PurchaseOrders/{PurchaseOrderID}/Attachments/{AttachmentID}": {
      "get": {
        "description": "Retrieves specific attachment for a specific purchase order using a unique attachment Id",
        "summary": "getPurchaseOrderAttachmentById",
        "tags": [
          "Accounting"
        ],
        "operationId": "getPurchaseOrderAttachmentById",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      }
    },
    "/PurchaseOrders/{PurchaseOrderID}/Attachments/{FileName}": {
      "get": {
        "description": "Retrieves a specific attachment for a specific purchase order by filename",
        "summary": "getPurchaseOrder≠AttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "getPurchaseOrder≠AttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates a specific attachment for a specific purchase order by filename",
        "summary": "updatePurchaseOrderAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "updatePurchaseOrderAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates attachment for a specific purchase order",
        "summary": "createPurchaseOrderAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "createPurchaseOrderAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments"
            ]
          }
        ]
      }
    },
    "/Quotes": {
      "get": {
        "description": "Retrieves sales quotes",
        "summary": "getQuotes",
        "tags": [
          "Accounting"
        ],
        "operationId": "getQuotes",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Create one or more quotes",
        "summary": "createQuotes",
        "tags": [
          "Accounting"
        ],
        "operationId": "createQuotes",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates or creates one or more quotes",
        "summary": "updateOrCreateQuotes",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateOrCreateQuotes",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/Quotes/{QuoteID}": {
      "get": {
        "description": "Retrieves a specific quote using a unique quote Id",
        "summary": "getQuote",
        "tags": [
          "Accounting"
        ],
        "operationId": "getQuote",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates a specific quote",
        "summary": "updateQuote",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateQuote",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/Quotes/{QuoteID}/History": {
      "get": {
        "description": "Retrieves history records of a specific quote",
        "summary": "getQuoteHistory",
        "tags": [
          "Accounting"
        ],
        "operationId": "getQuoteHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates a history record for a specific quote",
        "summary": "createQuoteHistory",
        "tags": [
          "Accounting"
        ],
        "operationId": "createQuoteHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/Quotes/{QuoteID}/pdf": {
      "get": {
        "description": "Retrieves a specific quote as a PDF file using a unique quote Id",
        "summary": "getQuoteAsPdf",
        "tags": [
          "Accounting"
        ],
        "operationId": "getQuoteAsPdf",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      }
    },
    "/Quotes/{QuoteID}/Attachments": {
      "get": {
        "description": "Retrieves attachments for a specific quote",
        "summary": "getQuoteAttachments",
        "tags": [
          "Accounting"
        ],
        "operationId": "getQuoteAttachments",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      }
    },
    "/Quotes/{QuoteID}/Attachments/{AttachmentID}": {
      "get": {
        "description": "Retrieves a specific attachment from a specific quote using a unique attachment Id",
        "summary": "getQuoteAttachmentById",
        "tags": [
          "Accounting"
        ],
        "operationId": "getQuoteAttachmentById",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      }
    },
    "/Quotes/{QuoteID}/Attachments/{FileName}": {
      "get": {
        "description": "Retrieves a specific attachment from a specific quote by filename",
        "summary": "getQuoteAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "getQuoteAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates a specific attachment from a specific quote by filename",
        "summary": "updateQuoteAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateQuoteAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates attachment for a specific quote",
        "summary": "createQuoteAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "createQuoteAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments"
            ]
          }
        ]
      }
    },
    "/Receipts": {
      "get": {
        "description": "Retrieves draft expense claim receipts for any user",
        "summary": "getReceipts",
        "tags": [
          "Accounting"
        ],
        "operationId": "getReceipts",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates draft expense claim receipts for any user",
        "summary": "createReceipt",
        "tags": [
          "Accounting"
        ],
        "operationId": "createReceipt",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/Receipts/{ReceiptID}": {
      "get": {
        "description": "Retrieves a specific draft expense claim receipt by using a unique receipt Id",
        "summary": "getReceipt",
        "tags": [
          "Accounting"
        ],
        "operationId": "getReceipt",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates a specific draft expense claim receipts",
        "summary": "updateReceipt",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateReceipt",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/Receipts/{ReceiptID}/Attachments": {
      "get": {
        "description": "Retrieves attachments for a specific expense claim receipt",
        "summary": "getReceiptAttachments",
        "tags": [
          "Accounting"
        ],
        "operationId": "getReceiptAttachments",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      }
    },
    "/Receipts/{ReceiptID}/Attachments/{AttachmentID}": {
      "get": {
        "description": "Retrieves a specific attachments from a specific expense claim receipts by using a unique attachment Id",
        "summary": "getReceiptAttachmentById",
        "tags": [
          "Accounting"
        ],
        "operationId": "getReceiptAttachmentById",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      }
    },
    "/Receipts/{ReceiptID}/Attachments/{FileName}": {
      "get": {
        "description": "Retrieves a specific attachment from a specific expense claim receipts by file name",
        "summary": "getReceiptAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "getReceiptAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates a specific attachment on a specific expense claim receipts by file name",
        "summary": "updateReceiptAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateReceiptAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates an attachment on a specific expense claim receipts by file name",
        "summary": "createReceiptAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "createReceiptAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments"
            ]
          }
        ]
      }
    },
    "/Receipts/{ReceiptID}/History": {
      "get": {
        "description": "Retrieves a history record for a specific receipt",
        "summary": "getReceiptHistory",
        "tags": [
          "Accounting"
        ],
        "operationId": "getReceiptHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates a history record for a specific receipt",
        "summary": "createReceiptHistory",
        "tags": [
          "Accounting"
        ],
        "operationId": "createReceiptHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/RepeatingInvoices": {
      "get": {
        "description": "Retrieves repeating invoices",
        "summary": "getRepeatingInvoices",
        "tags": [
          "Accounting"
        ],
        "operationId": "getRepeatingInvoices",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      }
    },
    "/RepeatingInvoices/{RepeatingInvoiceID}": {
      "get": {
        "description": "Retrieves a specific repeating invoice by using a unique repeating invoice Id",
        "summary": "getRepeatingInvoice",
        "tags": [
          "Accounting"
        ],
        "operationId": "getRepeatingInvoice",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      }
    },
    "/RepeatingInvoices/{RepeatingInvoiceID}/Attachments": {
      "get": {
        "description": "Retrieves attachments from a specific repeating invoice",
        "summary": "getRepeatingInvoiceAttachments",
        "tags": [
          "Accounting"
        ],
        "operationId": "getRepeatingInvoiceAttachments",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      }
    },
    "/RepeatingInvoices/{RepeatingInvoiceID}/Attachments/{AttachmentID}": {
      "get": {
        "description": "Retrieves a specific attachment from a specific repeating invoice",
        "summary": "getRepeatingInvoiceAttachmentById",
        "tags": [
          "Accounting"
        ],
        "operationId": "getRepeatingInvoiceAttachmentById",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      }
    },
    "/RepeatingInvoices/{RepeatingInvoiceID}/Attachments/{FileName}": {
      "get": {
        "description": "Retrieves a specific attachment from a specific repeating invoices by file name",
        "summary": "getRepeatingInvoiceAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "getRepeatingInvoiceAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments",
              "accounting.attachments.read"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates a specific attachment from a specific repeating invoices by file name",
        "summary": "updateRepeatingInvoiceAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateRepeatingInvoiceAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates an attachment from a specific repeating invoices by file name",
        "summary": "createRepeatingInvoiceAttachmentByFileName",
        "tags": [
          "Accounting"
        ],
        "operationId": "createRepeatingInvoiceAttachmentByFileName",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.attachments"
            ]
          }
        ]
      }
    },
    "/RepeatingInvoices/{RepeatingInvoiceID}/History": {
      "get": {
        "description": "Retrieves history record for a specific repeating invoice",
        "summary": "getRepeatingInvoiceHistory",
        "tags": [
          "Accounting"
        ],
        "operationId": "getRepeatingInvoiceHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions",
              "accounting.transactions.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates a  history record for a specific repeating invoice",
        "summary": "createRepeatingInvoiceHistory",
        "tags": [
          "Accounting"
        ],
        "operationId": "createRepeatingInvoiceHistory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.transactions"
            ]
          }
        ]
      }
    },
    "/Reports/TenNinetyNine": {
      "get": {
        "description": "Retrieve reports for 1099",
        "summary": "getReportTenNinetyNine",
        "tags": [
          "Accounting"
        ],
        "operationId": "getReportTenNinetyNine",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.reports.read",
              "accounting.reports.tenninetynine.read"
            ]
          }
        ]
      }
    },
    "/Reports/AgedPayablesByContact": {
      "get": {
        "description": "Retrieves report for aged payables by contact",
        "summary": "getReportAgedPayablesByContact",
        "tags": [
          "Accounting"
        ],
        "operationId": "getReportAgedPayablesByContact",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.reports.read"
            ]
          }
        ]
      }
    },
    "/Reports/AgedReceivablesByContact": {
      "get": {
        "description": "Retrieves report for aged receivables by contact",
        "summary": "getReportAgedReceivablesByContact",
        "tags": [
          "Accounting"
        ],
        "operationId": "getReportAgedReceivablesByContact",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.reports.read"
            ]
          }
        ]
      }
    },
    "/Reports/BalanceSheet": {
      "get": {
        "description": "Retrieves report for balancesheet",
        "summary": "getReportBalanceSheet",
        "tags": [
          "Accounting"
        ],
        "operationId": "getReportBalanceSheet",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.reports.read"
            ]
          }
        ]
      }
    },
    "/Reports/BankSummary": {
      "get": {
        "description": "Retrieves report for bank summary",
        "summary": "getReportBankSummary",
        "tags": [
          "Accounting"
        ],
        "operationId": "getReportBankSummary",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.reports.read"
            ]
          }
        ]
      }
    },
    "/Reports/{ReportID}": {
      "get": {
        "description": "Retrieves a specific report using a unique ReportID",
        "summary": "getReportFromId",
        "tags": [
          "Accounting"
        ],
        "operationId": "getReportFromId",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.reports.read"
            ]
          }
        ]
      }
    },
    "/Reports/BudgetSummary": {
      "get": {
        "description": "Retrieves report for budget summary",
        "summary": "getReportBudgetSummary",
        "tags": [
          "Accounting"
        ],
        "operationId": "getReportBudgetSummary",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.reports.read"
            ]
          }
        ]
      }
    },
    "/Reports/ExecutiveSummary": {
      "get": {
        "description": "Retrieves report for executive summary",
        "summary": "getReportExecutiveSummary",
        "tags": [
          "Accounting"
        ],
        "operationId": "getReportExecutiveSummary",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.reports.read"
            ]
          }
        ]
      }
    },
    "/Reports": {
      "get": {
        "description": "Retrieves a list of the organistaions unique reports that require a uuid to fetch",
        "summary": "getReportsList",
        "tags": [
          "Accounting"
        ],
        "operationId": "getReportsList",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.reports.read"
            ]
          }
        ]
      }
    },
    "/Reports/ProfitAndLoss": {
      "get": {
        "description": "Retrieves report for profit and loss",
        "summary": "getReportProfitAndLoss",
        "tags": [
          "Accounting"
        ],
        "operationId": "getReportProfitAndLoss",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.reports.read"
            ]
          }
        ]
      }
    },
    "/Reports/TrialBalance": {
      "get": {
        "description": "Retrieves report for trial balance",
        "summary": "getReportTrialBalance",
        "tags": [
          "Accounting"
        ],
        "operationId": "getReportTrialBalance",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.reports.read"
            ]
          }
        ]
      }
    },
    "/Setup": {
      "post": {
        "description": "Sets the chart of accounts, the conversion date and conversion balances",
        "summary": "postSetup",
        "tags": [
          "Accounting"
        ],
        "operationId": "postSetup",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings"
            ]
          }
        ]
      }
    },
    "/TaxRates": {
      "get": {
        "description": "Retrieves tax rates",
        "summary": "getTaxRates",
        "tags": [
          "Accounting"
        ],
        "operationId": "getTaxRates",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings",
              "accounting.settings.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Creates one or more tax rates",
        "summary": "createTaxRates",
        "tags": [
          "Accounting"
        ],
        "operationId": "createTaxRates",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates tax rates",
        "summary": "updateTaxRate",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateTaxRate",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings"
            ]
          }
        ]
      }
    },
    "/TrackingCategories": {
      "get": {
        "description": "Retrieves tracking categories and options",
        "summary": "getTrackingCategories",
        "tags": [
          "Accounting"
        ],
        "operationId": "getTrackingCategories",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings",
              "accounting.settings.read"
            ]
          }
        ]
      },
      "put": {
        "description": "Create tracking categories",
        "summary": "createTrackingCategory",
        "tags": [
          "Accounting"
        ],
        "operationId": "createTrackingCategory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings"
            ]
          }
        ]
      }
    },
    "/TrackingCategories/{TrackingCategoryID}": {
      "get": {
        "description": "Retrieves specific tracking categories and options using a unique tracking category Id",
        "summary": "getTrackingCategory",
        "tags": [
          "Accounting"
        ],
        "operationId": "getTrackingCategory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings",
              "accounting.settings.read"
            ]
          }
        ]
      },
      "post": {
        "description": "Updates a specific tracking category",
        "summary": "updateTrackingCategory",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateTrackingCategory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings"
            ]
          }
        ]
      },
      "delete": {
        "description": "Deletes a specific tracking category",
        "summary": "deleteTrackingCategory",
        "tags": [
          "Accounting"
        ],
        "operationId": "deleteTrackingCategory",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings"
            ]
          }
        ]
      }
    },
    "/TrackingCategories/{TrackingCategoryID}/Options": {
      "put": {
        "description": "Creates options for a specific tracking category",
        "summary": "createTrackingOptions",
        "tags": [
          "Accounting"
        ],
        "operationId": "createTrackingOptions",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings"
            ]
          }
        ]
      }
    },
    "/TrackingCategories/{TrackingCategoryID}/Options/{TrackingOptionID}": {
      "post": {
        "description": "Updates a specific option for a specific tracking category",
        "summary": "updateTrackingOptions",
        "tags": [
          "Accounting"
        ],
        "operationId": "updateTrackingOptions",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings"
            ]
          }
        ]
      },
      "delete": {
        "description": "Deletes a specific option for a specific tracking category",
        "summary": "deleteTrackingOptions",
        "tags": [
          "Accounting"
        ],
        "operationId": "deleteTrackingOptions",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings"
            ]
          }
        ]
      }
    },
    "/Users": {
      "get": {
        "description": "Retrieves users",
        "summary": "getUsers",
        "tags": [
          "Accounting"
        ],
        "operationId": "getUsers",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings",
              "accounting.settings.read"
            ]
          }
        ]
      }
    },
    "/Users/{UserID}": {
      "get": {
        "description": "Retrieves a specific user",
        "summary": "getUser",
        "tags": [
          "Accounting"
        ],
        "operationId": "getUser",
        "deprecated": false,
        "security": [
          {
            "OAuth2": [
              "accounting.settings",
              "accounting.settings.read"
            ]
          }
        ]
      }
    }
  },
  "security": [],
  "tags": [
    {
      "name": "Accounting",
      "description": ""
    }
  ]
}