{
    "swagger": "2.0",
    "info": {
        "title": "Spotify",
        "description": "The Spotify connector will give you access to your Library, Artists, Albums, Tracks and more!",
        "version": "1.0",
        "contact": {
            "name": "Daniel Laskewitz",
            "url": "https://youtube.com/daniellaskewitz",
            "email": "connectorsupport@laskewitz.io"
        }
    },
    "host": "api.spotify.com",
    "basePath": "/v1",
    "schemes": [
        "https"
    ],
    "paths": {
        "/albums/{id}": {
            "get": {
                "summary": "Get Album\n",
                "description": "Get Album",
                "operationId": "GetAlbum"
            }
        },
        "/albums/{id}/tracks": {
            "get": {
                "summary": "Get Album Tracks\n",
                "description": "Get Album Tracks",
                "operationId": "GetAlbumTracks"
            }
        },
        "/albums": {
            "get": {
                "summary": "Get Several Albums\n",
                "description": "Get Several Albums\n",
                "operationId": "GetSeveralAlbums"
            }
        },
        "/artists/{id}": {
            "get": {
                "summary": "Get Artist\n",
                "description": "Get Artist\n",
                "operationId": "GetArtist"
            }
        },
        "/artists/{id}/albums": {
            "get": {
                "summary": "Get Artist Albums",
                "description": "Get Artist Albums",
                "operationId": "GetArtistAlbums"
            }
        },
        "/artists/{id}/top-tracks": {
            "get": {
                "summary": "Get Artist Top Tracks",
                "description": "Get Artist Top Tracks",
                "operationId": "GetArtistTopTracks"
            }
        },
        "/artists/{id}/related-artists": {
            "get": {
                "summary": "Get Artist Related Artists",
                "description": "Get Artist Related Artists",
                "operationId": "GetArtistRelatedArtists"
            }
        },
        "/artists": {
            "get": {
                "summary": "Get Several Artists\n",
                "description": "Get Several Artists\n",
                "operationId": "GetSeveralArtists"
            }
        },
        "/shows/{id}": {
            "get": {
                "summary": "Get Show\n",
                "description": "Get Show\n",
                "operationId": "GetShow"
            }
        },
        "/shows/{id}/episodes": {
            "get": {
                "summary": "Get Show Episodes\n",
                "description": "Get Show Episodes\n",
                "operationId": "GetShowEpisodes"
            }
        },
        "/shows": {
            "get": {
                "summary": "Get Several Shows\n",
                "description": "Get Several Shows\n",
                "operationId": "GetSeveralShows"
            }
        },
        "/episodes": {
            "get": {
                "summary": "Get Several Episodes\n",
                "description": "Get Several Episodes\n",
                "operationId": "GetSeveralEpisodes"
            }
        },
        "/episodes/{id}": {
            "get": {
                "summary": "Get Episode\n",
                "description": "Get Episode\n",
                "operationId": "GetEpisode"
            }
        },
        "/tracks": {
            "get": {
                "summary": "Get Several Tracks\n",
                "description": "Get Several Tracks\n",
                "operationId": "GetSeveralTracks"
            }
        },
        "/tracks/{id}": {
            "get": {
                "summary": "Get Track\n",
                "description": "Get Track\n",
                "operationId": "GetTrack"
            }
        },
        "/me/albums": {
            "get": {
                "summary": "Get Saved Albums\n",
                "description": "Get Saved Albums\n",
                "operationId": "GetSavedAlbums"
            },
            "delete": {
                "summary": "Remove Albums\n",
                "description": "Remove Albums\n",
                "operationId": "RemoveAlbums"
            },
            "put": {
                "summary": "Save Albums\n",
                "description": "Save Albums\n",
                "operationId": "SaveAlbums"
            }
        },
        "/me/albums/contains": {
            "get": {
                "summary": "Check Saved Albums\n",
                "description": "Check Saved Albums\n",
                "operationId": "CheckSavedAlbums"
            }
        },
        "/me/tracks": {
            "get": {
                "summary": "Get User Saved Tracks",
                "description": "Get User Saved Tracks",
                "operationId": "GetUserSavedTracks"
            },
            "delete": {
                "summary": "Remove Tracks for Current User\n",
                "description": "Remove Tracks for Current User\n",
                "operationId": "RemoveTracksForCurrentUser"
            },
            "put": {
                "summary": "Save Tracks for Current User\n",
                "description": "Save Tracks for Current User\n",
                "operationId": "SaveTracksForCurrentUser"
            }
        },
        "/me/tracks/contains": {
            "get": {
                "summary": "Check User Saved Tracks",
                "description": "Check User Saved Tracks",
                "operationId": "CheckUserSavedTracks"
            }
        },
        "/me/episodes": {
            "get": {
                "summary": "Get User Saved Episodes",
                "description": "Get User Saved Episodes",
                "operationId": "GetUserSavedEpisodes"
            },
            "delete": {
                "summary": "Remove User Saved Episodes",
                "description": "Remove User Saved Episodes",
                "operationId": "RemoveUserSavedEpisodes"
            },
            "put": {
                "summary": "Save Episodes for User\n",
                "description": "Save Episodes for User\n",
                "operationId": "SaveEpisodesForUser"
            }
        },
        "/me/episodes/contains": {
            "get": {
                "summary": "Check User Saved Episodes",
                "description": "Check User Saved Episodes",
                "operationId": "CheckUserSavedEpisodes"
            }
        },
        "/me/shows": {
            "get": {
                "summary": "Get User Saved Shows",
                "description": "Get User Saved Shows",
                "operationId": "GetUserSavedShows"
            },
            "delete": {
                "summary": "Remove User Saved Shows",
                "description": "Remove User Saved Shows",
                "operationId": "RemoveUserSavedShows"
            },
            "put": {
                "summary": "Save Shows for Current User\n",
                "description": "Save Shows for Current User\n",
                "operationId": "SaveShowsForCurrentUser"
            }
        },
        "/me/shows/contains": {
            "get": {
                "summary": "Check User Saved Shows",
                "description": "Check User Saved Shows",
                "operationId": "CheckUserSavedShows"
            }
        },
        "/me/following": {
            "get": {
                "summary": "Get Followed Artists\n",
                "description": "Get Followed Artists\n",
                "operationId": "GetFollowedArtists"
            },
            "delete": {
                "summary": "Unfollow Artists or Users\n",
                "description": "Unfollow Artists or Users\n",
                "operationId": "UnfollowArtistsOrUsers"
            },
            "put": {
                "summary": "Follow Artists or Users\n",
                "description": "Follow Artists or Users\n",
                "operationId": "FollowArtistsOrUsers"
            }
        },
        "/me/following/contains": {
            "get": {
                "summary": "Check If User Follows Artists or Users\n",
                "description": "Check If User Follows Artists or Users\n",
                "operationId": "CheckIfUserFollowsArtistsOrUsers"
            }
        },
        "/me/player": {
            "get": {
                "summary": "Get Playback State\n",
                "description": "Get Playback State\n",
                "operationId": "GetPlaybackState"
            },
            "put": {
                "summary": "Transfer Playback\n",
                "description": "Transfer Playback\n",
                "operationId": "TransferPlayback"
            }
        },
        "/me/player/devices": {
            "get": {
                "summary": "Get Available Devices\n",
                "description": "Get Available Devices\n",
                "operationId": "GetAvailableDevices"
            }
        },
        "/me/player/currently-playing": {
            "get": {
                "summary": "Get Currently Playing Track\n",
                "description": "Get Currently Playing Track\n",
                "operationId": "GetCurrentlyPlayingTrack"
            }
        },
        "/me/player/play": {
            "put": {
                "summary": "Start Resume Playback",
                "description": "Start Resume Playback",
                "operationId": "Start_resumePlayback"
            }
        },
        "/me/player/pause": {
            "put": {
                "summary": "Pause Playback",
                "description": "Pause Playback",
                "operationId": "PausePlayback"
            }
        },
        "/me/player/next": {
            "post": {
                "summary": "Skip To Next\n",
                "description": "Skip To Next\n",
                "operationId": "SkipToNext"
            }
        },
        "/me/player/previous": {
            "post": {
                "summary": "Skip To Previous\n",
                "description": "Skip To Previous\n",
                "operationId": "SkipToPrevious"
            }
        },
        "/me/player/seek": {
            "put": {
                "summary": "Seek To Position\n",
                "description": "Seek To Position\n",
                "operationId": "SeekToPosition"
            }
        },
        "/me/player/repeat": {
            "put": {
                "summary": "Set Repeat Mode",
                "description": "Set Repeat Mode\n",
                "operationId": "SetRepeatMode"
            }
        },
        "/me/player/volume": {
            "put": {
                "summary": "Set Playback Volume\n",
                "description": "Set Playback Volume\n",
                "operationId": "SetPlaybackVolume"
            }
        },
        "/me/player/shuffle": {
            "put": {
                "summary": "Toggle Playback Shuffle\n",
                "description": "Toggle Playback Shuffle\n",
                "operationId": "TogglePlaybackShuffle"
            }
        },
        "/me/player/recently-played": {
            "get": {
                "summary": "Get Recently Played Tracks\n",
                "description": "Get Recently Played Tracks\n",
                "operationId": "GetRecentlyPlayedTracks"
            }
        },
        "/me/player/queue": {
            "post": {
                "summary": "Add Item to Playback Queue\n",
                "description": "Add Item to Playback Queue\n",
                "operationId": "AddItemToPlaybackQueue"
            }
        },
        "/me/top/artists": {
            "get": {
                "summary": "Get User Top Artists",
                "description": "Get User Top Artists",
                "operationId": "GetUserTopArtists"
            }
        },
        "/me/top/tracks": {
            "get": {
                "summary": "Get User Top Tracks",
                "description": "Get User Top Tracks",
                "operationId": "GetUserTopTracks"
            }
        },
        "/me": {
            "get": {
                "summary": "Get Current User Profile",
                "description": "Get Current User Profile",
                "operationId": "GetCurrentUserProfile"
            }
        },
        "/me/playlists": {
            "get": {
                "summary": "Get Current User Playlists",
                "description": "Get Current User Playlists",
                "operationId": "GetCurrentUserPlaylists"
            }
        },
        "/playlists/{playlist_id}/tracks": {
            "get": {
                "summary": "Get Playlist Items\n",
                "description": "Get Playlist Items\n",
                "operationId": "GetPlaylistItems"
            },
            "delete": {
                "summary": "Remove Playlist Items\n",
                "description": "Remove Playlist Items\n",
                "operationId": "RemovePlaylistItems"
            },
            "post": {
                "summary": "Add Items to Playlist\n",
                "description": "Add Items to Playlist\n",
                "operationId": "AddItemsToPlaylist"
            },
            "put": {
                "summary": "Update Playlist Items\n",
                "description": "Update Playlist Items\n",
                "operationId": "UpdatePlaylistItems"
            }
        },
        "/playlists/{playlist_id}/followers": {
            "delete": {
                "summary": "Unfollow Playlist\n",
                "description": "Unfollow Playlist\n",
                "operationId": "UnfollowPlaylist"
            },
            "put": {
                "summary": "Follow Playlist\n",
                "description": "Follow Playlist\n",
                "operationId": "FollowPlaylist"
            }
        },
        "/playlists/{playlist_id}/followers/contains": {
            "get": {
                "summary": "Check if Users Follow Playlist\n",
                "description": "Check if Users Follow Playlist\n",
                "operationId": "CheckIfUsersFollowPlaylist"
            }
        },
        "/playlists/{playlist_id}/images": {
            "get": {
                "summary": "Get Playlist Cover Image\n",
                "description": "Get Playlist Cover Image\n",
                "operationId": "GetPlaylistCoverImage"
            },
            "put": {
                "summary": "Add Custom Playlist Cover Image\n",
                "description": "Add Custom Playlist Cover Image\n",
                "operationId": "AddCustomPlaylistCoverImage"
            }
        },
        "/playlists/{playlist_id}": {
            "get": {
                "summary": "Get Playlist\n",
                "description": "Get Playlist\n",
                "operationId": "GetPlaylist"
            },
            "put": {
                "summary": "Change Playlist Details\n",
                "description": "Change Playlist Details\n",
                "operationId": "ChangePlaylistDetails"
            }
        },
        "/users/{user_id}/playlists": {
            "get": {
                "summary": "Get User Playlists",
                "description": "Get User Playlists",
                "operationId": "GetUserPlaylists"
            },
            "post": {
                "summary": "Create Playlist\n",
                "description": "Create Playlist\n",
                "operationId": "CreatePlaylist"
            }
        },
        "/users/{user_id}": {
            "get": {
                "summary": "Get User Profile",
                "description": "Get User Profile",
                "operationId": "GetUserProfile"
            }
        },
        "/browse/categories/{category_id}": {
            "get": {
                "summary": "Get Single Browse Category\n",
                "description": "Get Single Browse Category\n",
                "operationId": "GetSingleBrowseCategory"
            }
        },
        "/browse/categories/{category_id}/playlists": {
            "get": {
                "summary": "Get Category Playlists",
                "description": "Get Category Playlists",
                "operationId": "GetCategoryPlaylists"
            }
        },
        "/browse/categories": {
            "get": {
                "summary": "Get Several Browse Categories\n",
                "description": "Get Several Browse Categories\n",
                "operationId": "GetSeveralBrowseCategories"
            }
        },
        "/browse/featured-playlists": {
            "get": {
                "summary": "Get Featured Playlists\n",
                "description": "Get Featured Playlists\n",
                "operationId": "GetFeaturedPlaylists"
            }
        },
        "/browse/new-releases": {
            "get": {
                "summary": "Get New Releases\n",
                "description": "Get New Releases\n",
                "operationId": "GetNewReleases"
            }
        },
        "/audio-features/{id}": {
            "get": {
                "summary": "Get Track Audio Features",
                "description": "Get Track Audio Features",
                "operationId": "GetTrackAudioFeatures"
            }
        },
        "/recommendations": {
            "get": {
                "summary": "Get Recommendations\n",
                "description": "Get Recommendations\n",
                "operationId": "GetRecommendations"
            }
        },
        "/recommendations/available-genre-seeds": {
            "get": {
                "summary": "Get Available Genre Seeds\n",
                "description": "Get Available Genre Seeds\n",
                "operationId": "GetAvailableGenreSeeds"
            }
        },
        "/search": {
            "get": {
                "summary": "Search for Item\n",
                "description": "Search for Item\n",
                "operationId": "SearchForItem"
            }
        },
        "/audio-analysis/{id}": {
            "get": {
                "summary": "Get Track Audio Analysis",
                "description": "Get Track Audio Analysis",
                "operationId": "GetTrackAudioAnalysis"
            }
        },
        "/markets": {
            "get": {
                "summary": "Get Available Markets\n",
                "description": "Get Available Markets\n",
                "operationId": "GetAvailableMarkets"
            }
        }
    },
    "securityDefinitions": {
        "oauth2_auth": {
            "type": "oauth2",
            "flow": "accessCode",
            "authorizationUrl": "https://accounts.spotify.com/authorize",
            "tokenUrl": "https://accounts.spotify.com/api/token",
            "scopes": {
                "ugc-image-upload user-modify-playback-state user-read-playback-state user-read-currently-playing user-follow-modify user-follow-read user-read-recently-played user-read-playback-position user-top-read playlist-read-collaborative playlist-modify-public playlist-read-private playlist-modify-private app-remote-control streaming user-read-email user-read-private user-library-modify user-library-read": "ugc-image-upload user-modify-playback-state user-read-playback-state user-read-cu[...]"
            }
        }
    },
    "security": [{
            "oauth2_auth": [
                "ugc-image-upload user-modify-playback-state user-read-playback-state user-read-currently-playing user-follow-modify user-follow-read user-read-recently-played user-read-playback-position user-top-read playlist-read-collaborative playlist-modify-public playlist-read-private playlist-modify-private app-remote-control streaming user-read-email user-read-private user-library-modify user-library-read"
            ]
        }
    ],
    "tags": []
}
