{
  "swagger": "2.0",
  "info": {
    "title": "Spotify",
    "description": "The Spotify connector will give you access to your Library, Artists, Albums, Tracks and more!",
    "version": "1.0",
    "contact": {
      "name": "Daniel Laskewitz | Sogeti",
      "url": "https://youtube.com/daniellaskewitz",
      "email": "connectorsupport@laskewitz.io"
    }
  },
  "host": "api.spotify.com",
  "basePath": "/",
  "schemes": ["https"],
  "paths": {
    "/v1/me/albums": {
      "get": {
        "summary": "Get User's Saved Albums",
        "description": "Get a list of the albums saved in the current Spotify user's 'Your Music' library.",
        "operationId": "GetSavedAlbums"
      }
    },
    "/v1/me": {
      "get": {
        "summary": "Get Current User's Profile",
        "description": "Get detailed profile information about the current user (including the current user's username).",
        "operationId": "GetUserProfile"
      }
    },
    "/v1/me/top/artists": {
      "get": {
        "summary": "Get a User's Top Artists",
        "description": "Get the current user's top artists based on calculated affinity.",
        "operationId": "GetTopArtists"
      }
    },
    "/v1/browse/new-releases": {
      "get": {
        "parameters": [
          {
            "name": "country",
            "description": "Provide this parameter if you want the list of returned items to be relevant to a particular country. If omitted, the returned items will be relevant to all countries.",
            "in": "query",
            "required": false,
            "type": "string",
            "x-ms-dynamic-values": {
              "operationId": "GetAvailableMarkets",
              "value-collection": "Markets"
            }
          }
        ],
        "summary": "Get All New Releases",
        "description": "A list of new album releases featured in Spotify (Example: 'Browse' tab on the Spotify player).",
        "operationId": "GetNewReleases"
      }
    },
    "/v1/markets": {
      "get": {
        "summary": "Get Available Markets",
        "description": "Get the list of markets where Spotify is available.",
        "operationId": "GetAvailableMarkets"
      }
    }
  },
  "securityDefinitions": {
    "oauth2_auth": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://accounts.spotify.com/authorize",
      "tokenUrl": "https://accounts.spotify.com/api/token",
      "scopes": {
        "user-read-recently-played user-read-currently-playing user-modify-playback-state user-read-playback-state user-library-modify user-library-read user-top-read playlist-modify-private playlist-read-private playlist-read-collaborative user-follow-modify user-follow-read": "user-read-recently-played user-read-currently-playing user-modify-playback-state user-read-playback-state user-library-modify user-library-read user-top-read playlist-modify-private playlist-read-private playlist-read-co[...]"
      }
    }
  },
  "security": [
    {
      "oauth2_auth": [
        "user-read-recently-played user-read-currently-playing user-modify-playback-state user-read-playback-state user-library-modify user-library-read user-top-read playlist-modify-private playlist-read-private playlist-read-collaborative user-follow-modify user-follow-read"
      ]
    }
  ],
  "tags": []
}
