{
  "swagger": "2.0",
  "info": {
    "title": "Xero Payroll - UK",
    "description": "Xero Payroll - UK community connector",
    "version": "1.0",
    "contact": {
      "name": "Troy Taylor",
      "url": "https://www.hitachisolutions.com",
      "email": "ttaylor@hitachisolutions.com"
    }
  },
  "host": "api.xero.com",
  "basePath": "/payroll.xro/2.0/",
  "schemes": [
    "https"
  ],
  "paths": {
    "/employees/{employeeID}": {
      "get": {
        "summary": "Retrieve a payroll employee",
        "description": "Allows you to retrieve details of a payroll employee in a Xero organisation",
        "operationId": "EmployeesGetA"
      },
      "put": {
        "summary": "Update a payroll employee",
        "description": "Allows you to update a payroll employee in a Xero organisation",
        "operationId": "EmployeesUpdate"
      }
    },
    "/employees": {
      "get": {
        "summary": "Retrieve employees",
        "description": "Retrieves a list of active employees",
        "operationId": "EmployeesGet"
      },
      "post": {
        "summary": "Add a payroll employee",
        "description": "Allows you to add a payroll employee in a Xero organisation",
        "operationId": "EmployeesCreate"
      }
    },
    "/timesheets": {
      "get": {
        "summary": "Retrieve payroll timesheets",
        "description": "Retrieves all Payroll Timesheets in a Xero organisation",
        "operationId": "TimesheetsGet"
      }
    },
    "/Timesheet/{timesheetID}": {
      "get": {
        "summary": "Retrieve a timesheet",
        "description": "Retrieves a Payroll Timesheet in a Xero organisation using timesheet identifier",
        "operationId": "TimesheetsGetA"
      },
      "delete": {
        "summary": "Delete a timesheet",
        "description": "Use this method to delete a timesheet",
        "operationId": "TimesheetDelete"
      }
    },
    "/timesheets/": {
      "post": {
        "summary": "Add a payroll timesheet",
        "description": "Use this method to add a payroll timesheet.",
        "operationId": "TimesheetsCreate"
      }
    },
    "/timesheets/{timesheetID}/approve": {
      "post": {
        "summary": "Approve a timesheet",
        "description": "Use this method to approve a timesheet.",
        "operationId": "TimesheetApprove"
      }
    },
    "/timesheets/{timesheetID}/lines": {
      "post": {
        "summary": "Add a timesheet line to payroll timesheet",
        "description": "Use this method to add a timesheet line to a payroll timesheet.",
        "operationId": "TimesheetLineCreate"
      }
    },
    "/timesheets/{timesheetID}/lines/{timesheetLineID}": {
      "delete": {
        "summary": "Delete a timesheet line",
        "description": "Use this method to delete a timesheet line from a payroll timesheet.",
        "operationId": "TimesheetLineDelete"
      },
      "put": {
        "summary": "Update a timesheet line",
        "description": "Use this method to update a timesheet line of a payroll timesheet.",
        "operationId": "TimesheetLineUpdate"
      }
    },
    "/reimbursements": {
      "get": {
        "summary": "Retrieve reimbursements",
        "description": "Retrieve all reimbursements.",
        "operationId": "ReimbursementsGet"
      },
      "post": {
        "summary": "Add a reimbursement",
        "description": "Add a reimbursement to an account",
        "operationId": "ReimbursementsCreate"
      }
    },
    "/reimbursements/{reimbursementID}": {
      "get": {
        "summary": "Retrieve a payroll reimbursement",
        "description": "Retrieve the details of a reimbursement.",
        "operationId": "ReimbursementsGetA"
      }
    }
  },
  "securityDefinitions": {
    "oauth2_auth": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://login.xero.com/identity/connect/authorize",
      "tokenUrl": "https://identity.xero.com/connect/token",
      "scopes": {
        "accounting.transactions accounting.transactions.read accounting.reports.read accounting.reports.tenninetynine.read accounting.journals.read accounting.settings accounting.settings.read accounting.contacts accounting.contacts.read accounting.attachments accounting.attachments.read": "accounting.transactions accounting.transactions.read accounting.reports.read accounting.reports.tenninetynine.read accounting.journals.read accounting.settings accounting.settings.read accounting.contacts ac[...]"
      }
    }
  },
  "security": [
    {
      "oauth2_auth": [
        "accounting.transactions accounting.transactions.read accounting.reports.read accounting.reports.tenninetynine.read accounting.journals.read accounting.settings accounting.settings.read accounting.contacts accounting.contacts.read accounting.attachments accounting.attachments.read"
      ]
    }
  ],
  "tags": []
}
