{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Azure AD Identity Protection",
    "description": "Identity Protection is a tool that allows organizations to discover, investigate, and remediate identity-based risks in their environment.",
    "contact": {
      "name": "Microsoft",
      "url": "https://azure.microsoft.com/",
      "email": "azuresentinel@microsoft.com"
    }
  },
  "host": "graph.microsoft.com",
  "basePath": "/",
  "schemes": [
    "https"
  ],
  "paths": {
    "/beta/riskyUsers/{Id}": {
      "get": {
        "summary": "Get risky user",
        "description": "Get a specific risky user and its properties",
        "operationId": "GetRiskUser",
        "deprecated": false
      }
    },
    "/beta/riskyUsers/confirmCompromised": {
      "post": {
        "summary": "Confirm a risky user as compromised",
        "description": "Confirm a risky user as compromised",
        "operationId": "ConfirmRiskUser"
      }
    },
    "/beta/riskDetections/{Id}": {
      "get": {
        "summary": "Get risk detections",
        "description": "Get riskDetections ",
        "operationId": "riskDetections",
        "deprecated": false
      }
    },
    "/beta/riskyUsers/dismiss": {
      "post": {
        "summary": "Dismiss a risky user",
        "description": "Dismiss a risky user",
        "operationId": "DismissRiskUser"
      }
    },
    "/beta/riskyUsers/{Id}/history": {
      "get": {
        "summary": "Get the risk history of a risky user",
        "description": "Get the risk history",
        "operationId": "GetRiskUserHistory"
      }
    }
  },
  "securityDefinitions": {
    "oauth2_auth": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://login.windows.net/common/oauth2/authorize",
      "tokenUrl": "https://login.windows.net/common/oauth2/authorize",
      "scopes": {
        "Directory.ReadWrite.All": "Directory.ReadWrite.All",
        "Group.ReadWrite.All": "Group.ReadWrite.All",
        "User.ReadWrite.All": "User.ReadWrite.All",
        "offline_access": "offline_access",
        "IdentityRiskEvent.Read.All": "IdentityRiskEvent.Read.All",
        "IdentityRiskEvent.ReadWrite.All": "IdentityRiskEvent.ReadWrite.All",
        "IdentityRiskyUser.Read.All": "IdentityRiskyUser.Read.All",
        "IdentityRiskyUser.ReadWrite.All": "IdentityRiskyUser.ReadWrite.All"
      }
    }
  },
  "security": [
    {
      "oauth2_auth": [
        "Directory.ReadWrite.All",
        "Group.ReadWrite.All",
        "User.ReadWrite.All",
        "offline_access",
        "IdentityRiskEvent.Read.All",
        "IdentityRiskEvent.ReadWrite.All",
        "IdentityRiskyUser.Read.All",
        "IdentityRiskyUser.ReadWrite.All"
      ]
    }
  ],
  "tags": []
}