{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Strava",
    "description": "This is a connector for the Strava API, Strava is a service for tracking human exercise which incorporates social network features. It is mostly used for cycling and running using GPS data. The connector gives you the opportunity to get your activities/clubs and other information from Strava.",
    "contact": {
      "name": "Richard Wierenga",
      "url": "https://developers.strava.com/",
      "email": "rwconnectors@gmail.com"
    }
  },
  "host": "www.strava.com",
  "basePath": "/api/v3/",
  "schemes": ["https"],
  "paths": {
    "/athletes/{id}/stats": {
      "get": {
        "summary": "Get Athlete Stats",
        "description": "Returns the activity stats of an athlete. Only includes data from activities set to Everyone visibility.",
        "operationId": "GetAthleteStats"
      }
    },
    "/athlete": {
      "get": {
        "summary": "Get Authenticated Athlete",
        "description": "Returns the currently authenticated athlete. Tokens with profile:read_all scope will receive a detailed athlete representation; all others will receive a summary representation.",
        "operationId": "GetAuthenticatedAthlete"
      }
    },
    "/athlete/activities": {
      "get": {
        "summary": "List Athlete Activities",
        "description": "Returns the activities of an athlete for a specific identifier. Requires activity:read. Only Me activities will be filtered out unless requested by a token with activity:read_all.",
        "operationId": "ListAthleteActivities"
      }
    },
    "/athlete/clubs": {
      "get": {
        "summary": "List Athlete Clubs",
        "description": "Returns a list of the clubs whose membership includes the authenticated athlete.",
        "operationId": "ListAthleteClubs"
      }
    },
    "/segments/{id}": {
      "get": {
        "summary": "Get Segment",
        "description": "Returns the specified segment. read_all scope required in order to retrieve athlete-specific segment information, or to retrieve private segments.",
        "operationId": "GetSegment"
      }
    },
    "/segments/starred": {
      "get": {
        "summary": "List Starred Segments",
        "description": "List of the authenticated athlete's starred segments. Private segments are filtered out unless requested by a token with read_all scope.",
        "operationId": "ListStarredSegments"
      }
    },
    "/activities/{id}": {
      "get": {
        "summary": "Get Activity",
        "description": "Returns the given activity that is owned by the authenticated athlete. Requires activity:read for Everyone and Followers activities. Requires activity:read_all for Only Me activities.",
        "operationId": "GetActivity"
      }
    },
    "/activities/{id}/laps": {
      "get": {
        "summary": "List Activity Laps",
        "description": "Returns the laps of an activity identified by an identifier. Requires activity:read for Everyone and Followers activities. Requires activity:read_all for Only Me activities.",
        "operationId": "ListActivityLaps"
      }
    },
    "/activities/{id}/comments": {
      "get": {
        "summary": "List Activity Comments",
        "description": "Returns the comments on the given activity. Requires activity:read for Everyone and Followers activities. Requires activity:read_all for Only Me activities.",
        "operationId": "ListActivityComments"
      }
    },
    "/activities/{id}/kudos": {
      "get": {
        "summary": "List Activity Kudoers",
        "description": "Returns the athletes who kudoed an activity identified by an identifier. Requires activity:read for Everyone and Followers activities. Requires activity:read_all for Only Me activities.",
        "operationId": "ListActivityKudoers"
      }
    },
    "/clubs/{id}": {
      "get": {
        "summary": "Get Club",
        "description": "Returns a given club using its identifier.",
        "operationId": "GetClub"
      }
    },
    "/clubs/{id}/members": {
      "get": {
        "summary": "List Club Members",
        "description": "Returns a list of the athletes who are members of a given club.",
        "operationId": "ListClubMembers"
      }
    },
    "/clubs/{id}/admins": {
      "get": {
        "summary": "List Club Administrators",
        "description": "Returns a list of the administrators of a given club.",
        "operationId": "ListClubAdministrators"
      }
    },
    "/clubs/{id}/activities": {
      "get": {
        "summary": "List Club Activities",
        "description": "Retrieve recent activities from members of a specific club. The authenticated athlete must belong to the requested club in order to hit this endpoint. Pagination is supported. Athlete profile visibility is respected for all activities.",
        "operationId": "ListClubActivities"
      }
    }
  },
  "securityDefinitions": {
    "oauth2_auth": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://www.strava.com/api/v3/oauth/authorize",
      "tokenUrl": "https://www.strava.com/api/v3/oauth/token",
      "scopes": {
        "activity:read": "activity:read"
      }
    }
  },
  "security": [
    {
      "oauth2_auth": ["activity:read"]
    }
  ],
  "tags": []
}
