{
  "swagger": "2.0",
  "info": {
    "title": "Square Business",
    "description": "Square helps millions of sellers run their business - from secure credit card processing to point of sale solutions. This connector contains actions for the following endpoints: Loyalty, Gift Cards, Bookings, Business, Team, Financials, Online and Auth.",
    "version": "1.2",
    "contact": {
      "name": "Troy Taylor",
      "url": "https://www.hitachisolutions.com",
      "email": "ttaylor@hitachisolutions.com"
    }
  },
  "host": "connect.squareupsandbox.com",
  "basePath": "/v2",
  "schemes": [
    "https"
  ],
  "paths": {
    "/bank-accounts": {
      "get": {
        "summary": "List bank accounts",
        "description": "Returns a list of BankAccount objects linked to a Square account.",
        "operationId": "BankAccountList"
      }
    },
    "/bank-accounts/by-v1-id/{v1_bank_account_id}": {
      "get": {
        "summary": "Get bank account by V1 ID",
        "description": "Returns details of a BankAccount identified by V1 bank account ID.",
        "operationId": "BankAccountGetV1"
      }
    },
    "/bank-accounts/{bank_account_id}": {
      "get": {
        "summary": "Get bank account",
        "description": "Returns details of a BankAccount linked to a Square account.",
        "operationId": "BankAccountGet"
      }
    },
    "/bookings": {
      "post": {
        "summary": "Create booking (Beta)",
        "description": "Creates a booking.",
        "operationId": "BookingCreate"
      }
    },
    "/bookings/availability/search": {
      "post": {
        "summary": "Search availability (Beta)",
        "description": "Searches for availabilities for booking.",
        "operationId": "BookingAvailability"
      }
    },
    "/bookings/business-booking-profile": {
      "get": {
        "summary": "Retrieve business booking profile (Beta)",
        "operationId": "BookingRetrieveProfile",
        "description": "Retrieves a seller's booking profile."
      }
    },
    "/bookings/team-member-booking-profiles": {
      "get": {
        "summary": "List team member booking profiles (Beta)",
        "description": "Lists booking profiles for team members.",
        "operationId": "BookingListTeamProfiles"
      }
    },
    "/cash-drawers/shifts": {
      "get": {
        "summary": "List cash drawer shifts",
        "description": "Provides the details for all of the cash drawer shifts for a location in a date range.",
        "operationId": "CashDrawerListShifts"
      }
    },
    "/cash-drawers/shifts/{shift_id}": {
      "get": {
        "summary": "Retrieve cash drawer shift",
        "description": "Provides the summary details for a single cash drawer shift.",
        "operationId": "CashDrawerRetrieveShift"
      }
    },
    "/cash-drawers/shifts/{shift_id}/events": {
      "get": {
        "summary": "List cash drawer shift events",
        "description": "Provides a paginated list of events for a single cash drawer shift.",
        "operationId": "CashDrawerListEvents"
      }
    },
    "/locations/{location_id}/checkouts": {
      "post": {
        "summary": "Create checkout",
        "description": "Links a checkoutId to a checkout_page_url that customers are directed to in order to provide their payment information using a payment processing workflow.",
        "operationId": "CheckoutCreate"
      }
    },
    "/devices/codes": {
      "get": {
        "summary": "List device codes",
        "description": "Lists all DeviceCodes associated with the merchant.",
        "operationId": "DeviceList"
      },
      "post": {
        "summary": "Create device code",
        "description": "Creates a DeviceCode that can be used to login to a Square Terminal device to enter the connected terminal mode.",
        "operationId": "DeviceCreate"
      }
    },
    "/devices/codes/{id}": {
      "get": {
        "summary": "Get device code",
        "description": "Retrieves DeviceCode with the associated ID.",
        "operationId": "DeviceGet"
      }
    },
    "/gift-cards/activities": {
      "get": {
        "summary": "List gift card activities (Beta)",
        "description": "Lists gift card activities. By default, you get gift card activities for all gift cards in the seller's account. You can optionally specify query parameters to filter the list. For example, you can get a list of gift card activities for a gift card, for all gift cards in a specific region, or for activities within a time window.",
        "operationId": "GiftCardList"
      },
      "post": {
        "summary": "Create gift card activity (Beta)",
        "description": "Creates a gift card activity.",
        "operationId": "GiftCardCreate"
      }
    },
    "/gift-cards/from-gan": {
      "post": {
        "summary": "Retrieve gift card from GAN (Beta)",
        "description": "Retrieves a gift card using the gift card account number (GAN).",
        "operationId": "GiftCardRetrieveGAN"
      }
    },
    "/gift-cards/from-nonce": {
      "post": {
        "summary": "Retrieve gift card from nonce (Beta)",
        "description": "Retrieves a gift card using a nonce (a secure token) that represents the gift card.",
        "operationId": "GiftCardRetrieveNonce"
      }
    },
    "/gift-cards/{gift_card_id}/link-customer": {
      "post": {
        "summary": "Link customer to gift card (Beta)",
        "description": "Links a customer to a gift card",
        "operationId": "GiftCardLink"
      }
    },
    "/gift-cards/{gift_card_id}/unlink-customer": {
      "post": {
        "summary": "Unlink customer from gift card (Beta)",
        "description": "Unlinks a customer from a gift card.",
        "operationId": "GiftCardUnlink"
      }
    },
    "/gift-cards/{id}": {
      "get": {
        "summary": "Retrieve gift card (Beta)",
        "description": "Retrieves a gift card using its ID.",
        "operationId": "GiftCardRetrieve"
      }
    },
    "/labor/break-types": {
      "get": {
        "summary": "List break types",
        "description": "Returns a paginated list of BreakType instances for a business.",
        "operationId": "LaborListBreak"
      },
      "post": {
        "summary": "Create break type",
        "description": "Creates a new BreakType. A BreakType is a template for creating Break objects.",
        "operationId": "LaborCreateBreak"
      }
    },
    "/labor/break-types/{id}": {
      "get": {
        "summary": "Get break type",
        "description": "Returns a single BreakType specified by id.",
        "operationId": "LaborGetBreak"
      },
      "delete": {
        "summary": "Delete break type",
        "description": "Deletes an existing BreakType. A BreakType can be deleted even if it is referenced from a Shift.",
        "operationId": "LaborDeleteBreak"
      },
      "put": {
        "summary": "Update break type",
        "operationId": "LaborUpdateBreak",
        "description": "Updates an existing BreakType."
      }
    },
    "/labor/shifts": {
      "post": {
        "summary": "Create shift",
        "description": "Creates a new Shift. A Shift represents a complete workday for a single employee",
        "operationId": "LaborCreateShift"
      }
    },
    "/labor/shifts/search": {
      "post": {
        "summary": "Search shifts",
        "description": "Returns a paginated list of Shift records for a business.",
        "operationId": "LaborSearchShifts"
      }
    },
    "/labor/shifts/{id}": {
      "get": {
        "summary": "Get shift",
        "description": "Returns a single Shift specified by id.",
        "operationId": "LaborGetShift"
      },
      "delete": {
        "summary": "Delete shift",
        "description": "Deletes a shift",
        "operationId": "LaborDeleteShift"
      },
      "put": {
        "summary": "Update shift",
        "description": "Updates an existing Shift.",
        "operationId": "LaborUpdateShift"
      }
    },
    "/labor/team-member-wages": {
      "get": {
        "summary": "List team member wages",
        "description": "Returns a paginated list of TeamMemberWage instances for a business.",
        "operationId": "LaborListWages"
      }
    },
    "/labor/team-member-wages/{id}": {
      "get": {
        "summary": "Get team member wage",
        "description": "Returns a single TeamMemberWage specified by id.",
        "operationId": "LaborGetWage"
      }
    },
    "/labor/workweek-configs": {
      "get": {
        "summary": "List workweek configs",
        "description": "Returns a list of WorkweekConfig instances for a business.",
        "operationId": "LaborListConfigs"
      }
    },
    "/labor/workweek-configs/{id}": {
      "put": {
        "summary": "Update workweek config",
        "description": "Updates a WorkweekConfig.",
        "operationId": "LaborUpdateConfig"
      }
    },
    "/locations": {
      "get": {
        "summary": "List locations",
        "description": "Provides information of all locations of a business.",
        "operationId": "LocationList"
      },
      "post": {
        "summary": "Create location (Beta)",
        "description": "Creates a location.",
        "operationId": "LocationCreate"
      }
    },
    "/locations/{location_id}": {
      "get": {
        "summary": "Retrieve location",
        "description": "Retrieves details of a location. You can specify \"main\" as the location ID to retrieve details of the main location.",
        "operationId": "LocationRetrieve"
      },
      "put": {
        "summary": "Update location (Beta)",
        "description": "Updates a location.",
        "operationId": "LocationUpdate"
      }
    },
    "/loyalty/accounts": {
      "post": {
        "summary": "Create loyalty account",
        "description": "Creates a loyalty account.",
        "operationId": "LoyaltyCreateAccount"
      }
    },
    "/loyalty/accounts/search": {
      "post": {
        "summary": "Search loyalty accounts",
        "description": "Searches for loyalty accounts in a loyalty program.",
        "operationId": "LoyaltySearchAccounts"
      }
    },
    "/loyalty/accounts/{account_id}": {
      "get": {
        "summary": "Retrieve loyalty account",
        "operationId": "LoyaltyRetrieveAccount",
        "description": "Retrieves a loyalty account."
      }
    },
    "/loyalty/accounts/{account_id}/accumulate": {
      "post": {
        "summary": "Accumulate loyalty points",
        "description": "Adds points to a loyalty account.",
        "operationId": "LoyaltyAccumulatePoints"
      }
    },
    "/loyalty/accounts/{account_id}/adjust": {
      "post": {
        "summary": "Adjust loyalty points",
        "description": "Adds points to or subtracts points from a buyer's account. Use this endpoint only when you need to manually adjust points.",
        "operationId": "LoyaltyAdjustPoints"
      }
    },
    "/loyalty/events/search": {
      "post": {
        "summary": "Search loyalty events",
        "description": "Searches for loyalty events. A Square loyalty program maintains a ledger of events that occur during the lifetime of a buyer's loyalty account. Each change in the point balance (for example, points earned, points redeemed, and points expired) is recorded in the ledger. Using this endpoint, you can search the ledger for events.",
        "operationId": "LoyaltySearchEvents"
      }
    },
    "/loyalty/programs/{program_id}": {
      "get": {
        "summary": "Retrieve loyalty program",
        "description": "Retrieves the loyalty program in a seller's account, specified by the program ID or the keyword main.  Loyalty programs define how buyers can earn points and redeem points for rewards.",
        "operationId": "LoyaltyRetrieveProgram"
      }
    },
    "/loyalty/programs/{program_id}/calculate": {
      "post": {
        "summary": "Calculate loyalty points",
        "description": "Calculates the points a purchase earns. An application might call this endpoint to show the points that a buyer can earn with the specific purchase.",
        "operationId": "LoyaltyCalculatePoints"
      }
    },
    "/loyalty/rewards": {
      "post": {
        "summary": "Create loyalty reward",
        "description": "Creates a loyalty reward. After a reward is created, the points are locked and not available for the buyer to redeem another reward.",
        "operationId": "LoyaltyCreateReward"
      }
    },
    "/loyalty/rewards/search": {
      "post": {
        "summary": "Search loyalty rewards",
        "description": "Searches for loyalty rewards in a loyalty account.",
        "operationId": "LoyaltySearchRewards"
      }
    },
    "/loyalty/rewards/{reward_id}": {
      "get": {
        "summary": "Retrieve loyalty reward",
        "description": "Retrieves a loyalty reward.",
        "operationId": "LoyaltyRetrieveReward"
      },
      "delete": {
        "summary": "Delete loyalty reward",
        "description": "Deletes a loyalty reward. Returns the loyalty points back to the loyalty account. You cannot delete a reward that has reached the terminal state (REDEEMED).",
        "operationId": "LoyaltyDeleteReward"
      }
    },
    "/loyalty/rewards/{reward_id}/redeem": {
      "post": {
        "summary": "Redeem loyalty reward",
        "description": "Redeems a loyalty reward. After the reward reaches the terminal state, it cannot be deleted. In other words, points used for the reward cannot be returned to the account.",
        "operationId": "LoyaltyRedeemReward"
      }
    },
    "/merchants": {
      "get": {
        "summary": "List merchants",
        "description": "Returns Merchant information for a given access token.",
        "operationId": "MerchantList"
      }
    },
    "/merchants/{merchant_id}": {
      "get": {
        "summary": "Retrieve merchant",
        "description": "Retrieve a Merchant object for the given merchant_id.",
        "operationId": "MerchantRetrieve"
      }
    },
    "/mobile/authorization-code": {
      "post": {
        "summary": "Create mobile authorization code",
        "description": "Generates code to authorize a mobile application to connect to a Square card reader. Authorization codes are one-time-use and expire 60 minutes after being issued.",
        "operationId": "MobileAuthorizationCreate"
      }
    },
    "/sites": {
      "get": {
        "summary": "List sites",
        "description": "Lists the Square Online sites that belong to a seller.",
        "operationId": "SiteList"
      }
    },
    "/sites/{site_id}/snippet": {
      "get": {
        "summary": "Retrieve snippet",
        "description": "Retrieves your snippet from a Square Online site. A site can contain snippets from multiple snippet applications, but you can retrieve only the snippet that was added by your application.",
        "operationId": "SnippetRetrieve"
      },
      "delete": {
        "summary": "Delete snippet",
        "description": "Removes your snippet from a Square Online site.",
        "operationId": "SnippetDelete"
      },
      "post": {
        "summary": "Upsert snippet",
        "description": "Adds a snippet to a Square Online site or updates the existing snippet on the site. The snippet code is appended to the end of the head element on every page of the site, except checkout pages. A snippet application can add one snippet to a given site.",
        "operationId": "SnippetUpsert"
      }
    },
    "/team-members": {
      "post": {
        "summary": "Create team member",
        "description": "Creates a single TeamMember object.",
        "operationId": "TeamCreateMember"
      }
    },
    "/team-members/bulk-create": {
      "post": {
        "summary": "Bulk create team members",
        "description": "Creates multiple TeamMember objects.",
        "operationId": "TeamCreateBulkMembers"
      }
    },
    "/team-members/bulk-update": {
      "post": {
        "summary": "Bulk update team members",
        "description": "Updates multiple TeamMember objects.",
        "operationId": "TeamUpdateBulkMembers"
      }
    },
    "/team-members/search": {
      "post": {
        "summary": "Search team members",
        "description": "Returns a paginated list of TeamMember objects for a business.",
        "operationId": "TeamSearch"
      }
    },
    "/team-members/{team_member_id}": {
      "get": {
        "summary": "Retrieve team member",
        "description": "Retrieves a TeamMember object for the given TeamMember id.",
        "operationId": "TeamRetrieveMember"
      },
      "put": {
        "summary": "Update team member",
        "description": "Updates a single TeamMember object.",
        "operationId": "TeamUpdate"
      }
    },
    "/team-members/{team_member_id}/wage-setting": {
      "get": {
        "summary": "Retrieve wage setting",
        "description": "Retrieves a WageSetting object for a team member specified by TeamMember id.",
        "operationId": "TeamRetrieveWage"
      },
      "put": {
        "summary": "Update wage setting",
        "description": "Creates or updates a WageSetting object.",
        "operationId": "TeamUpdateWage"
      }
    }
  },
  "securityDefinitions": {
    "oauth2_auth": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://squareupsandbox.com/oauth2/authorize",
      "tokenUrl": "https://connect.squareupsandbox.com/oauth2/token",
      "scopes": {
        "BANK_ACCOUNTS_READ CASH_DRAWER_READ CUSTOMERS_READ CUSTOMERS_WRITE DEVICE_CREDENTIAL_MANAGEMENT EMPLOYEES_READ EMPLOYEES_WRITE INVENTORY_READ INVENTORY_WRITE ITEMS_READ ITEMS_WRITE LOYALTY_READ LOYALTY_WRITE MERCHANT_PROFILE_READ ORDERS_READ ORDERS_WRITE PAYMENTS_READ PAYMENTS_WRITE PAYMENTS_WRITE_ADDITIONAL_RECIPIENTS PAYMENTS_WRITE_IN_PERSON SETTLEMENTS_READ TIMECARDS_READ TIMECARDS_WRITE TIMECARDS_SETTINGS_READ TIMECARDS_SETTINGS_WRITE APPOINTMENTS_READ APPOINTMENTS_WRITE APPOINTMENT[...]"
      }
    }
  },
  "security": [
    {
      "oauth2_auth": [
        "BANK_ACCOUNTS_READ CASH_DRAWER_READ CUSTOMERS_READ CUSTOMERS_WRITE DEVICE_CREDENTIAL_MANAGEMENT EMPLOYEES_READ EMPLOYEES_WRITE INVENTORY_READ INVENTORY_WRITE ITEMS_READ ITEMS_WRITE LOYALTY_READ LOYALTY_WRITE MERCHANT_PROFILE_READ ORDERS_READ ORDERS_WRITE PAYMENTS_READ PAYMENTS_WRITE PAYMENTS_WRITE_ADDITIONAL_RECIPIENTS PAYMENTS_WRITE_IN_PERSON SETTLEMENTS_READ TIMECARDS_READ TIMECARDS_WRITE TIMECARDS_SETTINGS_READ TIMECARDS_SETTINGS_WRITE APPOINTMENTS_READ APPOINTMENTS_WRITE APPOINTMENT[...]"
      ]
    }
  ],
  "tags": []
}
