//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnowflakeV2CoreLogic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SnowflakeV2CoreLogic.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required parameter: &apos;{0}&apos; missing for requested operation: &apos;{1}&apos;..
        /// </summary>
        internal static string RequiredParameterIsMissed {
            get {
                return ResourceManager.GetString("RequiredParameterIsMissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value must be provided for data set.
        /// </summary>
        internal static string SnowflakeDataSetMissing {
            get {
                return ResourceManager.GetString("SnowflakeDataSetMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value must be provided for item id..
        /// </summary>
        internal static string SnowflakeItemIdMissing {
            get {
                return ResourceManager.GetString("SnowflakeItemIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value must be provided for item..
        /// </summary>
        internal static string SnowflakeItemMissing {
            get {
                return ResourceManager.GetString("SnowflakeItemMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value must be provided for table name..
        /// </summary>
        internal static string SnowflakeTableNameMissing {
            get {
                return ResourceManager.GetString("SnowflakeTableNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection has failed. Please check connector documentation and verify that your Snowflake instance meets connector limitations..
        /// </summary>
        internal static string TestConnectionFailed {
            get {
                return ResourceManager.GetString("TestConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection creation failed. Snowflake Error : {0}..
        /// </summary>
        internal static string TestConnectionFailedSnowflakeException {
            get {
                return ResourceManager.GetString("TestConnectionFailedSnowflakeException", resourceCulture);
            }
        }
    }
}
