name: 🐛 Bug report
description: File a connector bug here!
title: "[BUG] <title>"
labels: [bug]
body: 
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report. Remember to include sufficient details and context. If you have multiple bugs, please submit them in separate issues.
- type: dropdown
  id: connector-type
  attributes:
    label: Type of Connector
    options:
      - Certified Connector
      - Custom Connector
      - Independent Publisher Connector
  validations:
    required: true
- type: input
  id: connector-name
  attributes:
    label: Name of Connector
    placeholder: |
      Enter the name of the connector.
  validations:
    required: true
- type: textarea
  id: bug-description
  attributes:
    label: Describe the bug
    placeholder: |
      A clear and concise description of what the bug is.
  validations:
    required: true
- type: dropdown
  id: security-bug
  attributes:
    label: Is this a security bug?
    options:
      - Yes, this is a security bug
      - No, this is not a security bug
  validations:
    required: true
- type: dropdown
  id: severity
  attributes:
    label: What is the severity of this bug?
    options:
      - Severity 1 - Connector is broken or there's a very serious issue
      - Severity 2 - One or more important connector features are down
      - Severity 3 - Minor issue
  validations:
    required: true
- type: textarea
  id: reproduce
  attributes:
    label: To Reproduce
    placeholder: |
      Steps to reproduce the behavior.
  validations:
    required: true
- type: textarea
  id: expected-behavior
  attributes:
    label: Expected behavior
    placeholder: |
      A clear and concise description of what you expected to happen.
  validations:
    required: true    
- type: textarea
  attributes:
    label: Environment summary
    value: |
      Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build)
      CLI version (paconn --version)
      OS version
      Shell Type (e.g. bash, cmd.exe, Bash on Windows)
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    placeholder: |
      Add any other context about the problem here.
  validations:
    required: true
