name: 🚀 Feature request
description: Suggest an idea for an existing connector in this repository!
title: "[FEATURE REQUEST] <title>"
body: 
- type: markdown
  attributes:
    value: |
      New ideas for existing connectors can include support for new actions, triggers, and support for more endpoints. If you need to submit a request for a new connector, please use the New connector request template.
- type: dropdown
  id: connector-type
  attributes:
    label: Type of Connector
    options:
      - Certified Connector
      - Custom Connector
      - Independent Publisher Connector
  validations:
    required: true
- type: input
  id: connector-name
  attributes:
    label: Name of Connector
    placeholder: |
      Enter the name of the connector.
  validations:
    required: true
- type: textarea
  id: feature-related-problem
  attributes:
    label: Is your feature request related to a problem? Please describe.
    placeholder: |
      A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  validations:
    required: true
- type: textarea
  id: solution-description
  attributes:
    label: Describe the solution you'd like
    placeholder: |
      A clear and concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  id: solution-alternatives
  attributes:
    label: Describe alternatives you've considered
    placeholder: |
      A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: true
- type: textarea
  id: additional-context
  attributes:
    label: Additional context
    placeholder: |
      Add any other context or screenshots about the feature request here.
  validations:
    required: true
