name: 💡 New connector request
description: Specify a connector that you need!
title: "[CONNECTOR REQUEST] <title>"
body:
- type: input
  id: end-service-name
  attributes:
    label: Name of the end service.
    placeholder: |
      Enter the name of the end service.
  validations:
    required: true
- type: textarea
  id: potential-use-cases
  attributes:
    label:  Describe the potential use cases for this connector
  validations:
    required: true
- type: textarea
  id: helpful-triggers-actions
  attributes:
    label:  What would be the most helpful actions and triggers for this connector?
  validations:
    required: true    
- type: textarea
  id: additional-context
  attributes:
    label: Additional context
    placeholder: |
      Add any other context about this new connector.
  validations:
    required: true
