name: 🚧 Service Team Support Request
description: For select service teams to request CLI-team support for work such as new features, commands, etc.
title: "[SERVICE TEAM SUPPORT REQUEST] <title>"
body:
- type: textarea
  id: feature-work-requested
  attributes:
    label: Description of Feature or Work Requested
    placeholder: |
      Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.
  validations:
    required: true
- type: textarea
  id: target-date
  attributes:
    label: Target Date
    placeholder: |
      If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates, it will help us prioritize your request against other requests.
  validations:
    required: true
