{
  "swagger": "2.0",
  "info": {
    "title": "Xero Accounting",
    "description": "This connector is used to retrieve and make changes to Xero Accounting. Xero Accounting can be used for a variety of purposes such as creating transactions like invoices and credit notes, right through to extracting accounting data via our reports endpoint.",
    "version": "1.0",
    "contact": {
      "name": "Troy Taylor",
      "url": "https://www.hitachisolutions.com",
      "email": "ttaylor@hitachisolutions.com"
    }
  },
  "host": "api.xero.com",
  "basePath": "/api.xro/2.0/",
  "schemes": [
    "https"
  ],
  "paths": {
    "/Contacts": {
      "get": {
        "summary": "Get contacts",
        "description": "Get a list of contacts",
        "operationId": "ContactsGet"
      },
      "post": {
        "summary": "Create a contact",
        "description": "Use this method to create a contact record.",
        "operationId": "ContactsCreate"
      },
      "put": {
        "summary": "Update a contact",
        "description": "Use this method to update a contact record. When you are updating a contact you don\u2019t need to specify every element. If you exclude an element then the existing value will be preserved.",
        "operationId": "ContactsUpdate"
      }
    },
    "/Contacts/{ContactID}": {
      "get": {
        "summary": "Get a contact",
        "description": "Get a single contact",
        "operationId": "ContactsGetA"
      }
    },
    "/Invoices": {
      "get": {
        "summary": "Get invoices",
        "description": "Get a list of invoices",
        "operationId": "InvoicesGet"
      },
      "post": {
        "summary": "Create an invoice",
        "description": "Use this method to create an invoice",
        "operationId": "InvoicesCreate"
      }
    },
    "/Invoices/{InvoiceID}": {
      "get": {
        "summary": "Retrieve an invoice",
        "description": "Use this method to retrieve one or many invoices.",
        "operationId": "InvoicesGetA"
      }
    },
    "/Payments/": {
      "get": {
        "summary": "Get payments",
        "description": "Use this method to retrieve all payments for invoices and credit notes.",
        "operationId": "PaymentsGet"
      },
      "put": {
        "summary": "Create a payment",
        "description": "Use this method to apply payments to approved AR and AP invoices.",
        "operationId": "PaymentsCreate"
      }
    },
    "/Payments/{InvoiceID}": {
      "get": {
        "operationId": "PaymentsGetA",
        "summary": "Get a payment",
        "description": "Use this method to retrieve one payment for invoices and credit notes"
      }
    },
    "/PurchaseOrders": {
      "get": {
        "summary": "Get purchase orders",
        "description": "Use this method to retrieve purchase orders.",
        "operationId": "PurchaseOrdersGet"
      },
      "post": {
        "summary": "Create a purchase order",
        "description": "Use this method to create a purchase order",
        "operationId": "PurchaseOrdersCreate"
      }
    },
    "/PurchaseOrders/{PurchaseOrderID}": {
      "get": {
        "summary": "Get a purchase order",
        "description": "Use this method to retrieve one purchase order.",
        "operationId": "PurchaseOrdersGetA"
      }
    },
    "/BankTransfers": {
      "get": {
        "summary": "Get bank transfers",
        "description": "Allows you to retrieve any bank transfers",
        "operationId": "BankTransfersGet"
      },
      "put": {
        "summary": "Create a bank transfer",
        "description": "Use this method to create a bank transfer",
        "operationId": "BankTransferCreate"
      }
    },
    "/BankTransfers/{BankTransferID}": {
      "get": {
        "summary": "Get a bank transfer",
        "description": "Allows you to retrieve a bank transfer",
        "operationId": "BankTransferGetA"
      }
    }
  },
  "securityDefinitions": {
    "oauth2_auth": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://login.xero.com/identity/connect/authorize",
      "tokenUrl": "https://identity.xero.com/connect/token",
      "scopes": {
        "accounting.transactions accounting.transactions.read accounting.reports.read accounting.reports.tenninetynine.read accounting.journals.read accounting.settings accounting.settings.read accounting.contacts accounting.contacts.read accounting.attachments accounting.attachments.read offline_access": "accounting.transactions accounting.transactions.read accounting.reports.read accounting.reports.tenninetynine.read accounting.journals.read accounting.settings accounting.settings.read account[...]"
      }
    }
  },
  "security": [
    {
      "oauth2_auth": [
        "accounting.transactions accounting.transactions.read accounting.reports.read accounting.reports.tenninetynine.read accounting.journals.read accounting.settings accounting.settings.read accounting.contacts accounting.contacts.read accounting.attachments accounting.attachments.read offline_access"
      ]
    }
  ],
  "tags": []
}
