{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "Shopify Admin Content",
    "description": "The Shopify REST Admin API lets you build apps and other integrations for the Shopify admin.",
    "contact": {
      "name": "Hitachi Solutions",
      "email":"jlindstrom@hitachisolutions.com"
    }
  },
  "host": "thatapiguy.myshopify.com",
  "basePath": "/admin/api/2021-04/",
  "schemes": [
    "https"
  ],
  "paths": {
    "/blogs/{blog_id}/articles.json": {
      "get": {
        "description": "Retrieves a list of all articles from a certain blog",
        "summary": "Get a list of all articles of a blog",
        "tags": [
          "Article"
        ],
        "operationId": "ListBlogArticles",
        "deprecated": false
      },
      "post": {
        "description": "Creates a new article for a blog",
        "summary": "Create a new article",
        "tags": [
          "Article"
        ],
        "operationId": "CreateArticle",
        "deprecated": false
      }
    },
    "/blogs/{blog_id}/articles/{article_id}.json": {
      "get": {
        "description": "Retrieves a single article by article id and parent blog id",
        "summary": "Get a single article",
        "tags": [
          "Article"
        ],
        "operationId": "GetArticle",
        "deprecated": false
      },
      "put": {
        "description": "Updates an existing article of a blog",
        "summary": "Update an article",
        "tags": [
          "Article"
        ],
        "operationId": "UpdateArticle",
        "deprecated": false
      }
    },
    "/blogs.json": {
      "get": {
        "description": "Retrieves a list of all blogs for your store",
        "summary": "Get a list of all blogs",
        "tags": [
          "Blog"
        ],
        "operationId": "ListBlogs",
        "deprecated": false
      },
      "post": {
        "description": "Creates a new empty blog",
        "summary": "Create a new blog",
        "tags": [
          "Blog"
        ],
        "operationId": "CreateBlog",
        "deprecated": false
      }
    },
    "/blogs/{blog_id}.json": {
      "get": {
        "description": "Retrieves a single blog by its ID",
        "summary": "Get a single blog",
        "tags": [
          "Blog"
        ],
        "operationId": "GetBlog",
        "deprecated": false
      },
      "delete": {
        "description": "Removes an existing blog from a shop",
        "summary": "Delete a blog",
        "tags": [
          "Blog"
        ],
        "operationId": "DeleteBlog",
        "deprecated": false
      },
      "put": {
        "description": "Updates an existing blog",
        "summary": "Update a blog",
        "tags": [
          "Blog"
        ],
        "operationId": "UpdateBlog",
        "deprecated": false
      }
    },
    "/comments.json": {
      "get": {
        "description": "Retrieves a list of all comments",
        "summary": "Get a list of comments",
        "tags": [
          "comments"
        ],
        "operationId": "ListComments",
        "deprecated": false
      },
      "post": {
        "description": "Creates a new comment for an article",
        "summary": "Create a new comment",
        "tags": [
          "comments"
        ],
        "operationId": "CreateComment",
        "deprecated": false
      }
    },
    "/comments/{comment_id}.json": {
      "get": {
        "description": "Retrieves a single comment by its id",
        "summary": "Get a single comment",
        "tags": [
          "comments"
        ],
        "operationId": "GetComment",
        "deprecated": false
      },
      "put": {
        "description": "Updates an existing comment",
        "summary": "Update a comment",
        "tags": [
          "comments"
        ],
        "operationId": "UpdateComment",
        "deprecated": false
      }
    },
    "/comments/{comment_id}/spam.json": {
      "post": {
        "description": "Marks a comment as Spam",
        "summary": "Mark a comment as Spam",
        "tags": [
          "comments"
        ],
        "operationId": "MarkCommentSpam",
        "deprecated": false
      }
    },
    "/pages.json": {
      "get": {
        "description": "Retrieves all pages for a shop",
        "summary": "Get a list of all pages",
        "tags": [
          "Page"
        ],
        "operationId": "ListPages",
        "deprecated": false
      },
      "post": {
        "description": "Creates a new page for a shop",
        "summary": "Create a new page",
        "tags": [
          "Page"
        ],
        "operationId": "CreatePage",
        "deprecated": false
      }
    },
    "/pages/count.json": {
      "get": {
        "description": "Retrieves a count all pages for a shop",
        "summary": "Count all pages for a shop",
        "tags": [
          "Page"
        ],
        "operationId": "CountAllPages",
        "deprecated": false
      }
    },
    "/pages/{page_id}.json": {
      "get": {
        "description": "Retrieves a single page by its ID",
        "summary": "Get a single page",
        "tags": [
          "Page"
        ],
        "operationId": "GetPage",
        "deprecated": false
      },
      "delete": {
        "description": "Deletes a page by its ID",
        "summary": "Delete a page",
        "tags": [
          "Page"
        ],
        "operationId": "DeletePage",
        "deprecated": false
      },
      "put": {
        "description": "Updates an existing page",
        "summary": "Update a page",
        "tags": [
          "Page"
        ],
        "operationId": "UpdatePage",
        "deprecated": false
      }
    }
  },
"securityDefinitions": {
  "oauth2_auth": {
    "type": "oauth2",
    "flow": "accessCode",
    "authorizationUrl": "https://thatapiguy.myshopify.com/admin/oauth/authorize",
    "tokenUrl": "https://thatapiguy.myshopify.com/admin/oauth/access_token",
    "scopes": {
      "read_analytics": "read_analytics",
      "read_reports": "read_reports",
      "write_orders": "write_orders",
      "read_customers": "read_customers",
      "write_customers": "write_customers",
      "write_reports": "write_reports",
      "read_content": "read_content",
      "write_content": "write_content",
      "read_themes": "read_themes",
      "write_themes": "write_themes",
      "read_product_listings": "read_product_listings",
      "read_products": "read_products",
      "write_products": "write_products",
      "read_checkouts": "read_checkouts",
      "write_checkouts": "write_checkouts",
      "read_inventory": "read_inventory",
      "write_inventory": "write_inventory",
      "read_marketing_events": "read_marketing_events",
      "write_marketing_events": "write_marketing_events",
      "read_shopify_payments_disputes": "read_shopify_payments_disputes"
    }
  }
},
"security": [
  {
    "oauth2_auth": [
      "read_analytics",
      "read_reports",
      "write_orders",
      "read_customers",
      "write_customers",
      "write_reports",
      "read_content",
      "write_content",
      "read_themes",
      "write_themes",
      "read_product_listings",
      "read_products",
      "write_products",
      "read_checkouts",
      "write_checkouts",
      "read_inventory",
      "write_inventory",
      "read_marketing_events",
      "write_marketing_events",
      "read_shopify_payments_disputes"
    ]
  }
]
}