{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Google Photos",
    "description": "Integrate smart, easy-to-use photo and video features into your product and reach hundreds of millions of people who choose Google Photos.",
    "contact": {
      "name": "Julia Muiruri",
      "url": "https://developers.google.com/photos",
      "email": "juliamuiruri@microsoft.com"
    }
  },
  "host": "photoslibrary.googleapis.com",
  "basePath": "/",
  "schemes": [
    "https"
  ],
  "paths": {
    "/v1/albums": {
      "get": {
        "summary": "List Albums",
        "description": "Lists all albums shown to a user in the Albums tab of the Google Photos app.\n\n### HTTP request\n\n`GET https://photoslibrary.googleapis.com/v1/albums`\n\nThe URL uses [gRPC Transcoding](https://github.com/googleapis/googleapis/blob/master/google/api/http.proto) syntax.\n\n### Query parameters\n\n|Parameters|||\n| ---- | ---- | ----- |\n|`pageSize`|`integer`|Maximum number of albums to return in the response. Fewer albums might be returned than the specified number. The [...]",
        "operationId": "ListAlbums"
      },
      "post": {
        "summary": "Create New Album",
        "description": "Creates an album in a user's Google Photos library.\n\n### HTTP request\n\n`POST https://photoslibrary.googleapis.com/v1/albums`\n\nThe URL uses [gRPC Transcoding](https://github.com/googleapis/googleapis/blob/master/google/api/http.proto) syntax.\n\n### Request body\n\nThe request body contains data with the following structure:\n\nJSON representation\n\n```json\n{\n  \"album\": {\n    object (Album)\n  }\n}\n```\n\n|Fields|||\n|----|----|----|\n|`album`|`object` ([Album[...]",
        "operationId": "CreateAlbum"
      }
    },
    "/v1/albums/%7B%7BalbumId%7D%7D": {},
    "/v1/albums/%7B%7Balbum.id%7D%7D": {},
    "/v1/albums/%7B%7BalbumId%7D%7D:addEnrichment": {},
    "/v1/albums/%7B%7BalbumId%7D%7D:share": {},
    "/v1/albums/%7B%7BalbumId%7D%7D:unshare": {},
    "/v1/albums/%7B%7BalbumId%7D%7D:batchAddMediaItems": {},
    "/v1/albums/%7B%7BalbumId%7D%7D:batchRemoveMediaItems": {},
    "/v1/mediaItems": {
      "get": {
        "summary": "List Media Items",
        "description": "\nList all media items from a user's Google Photos library.\n\n### HTTP request\n\n`GET https://photoslibrary.googleapis.com/v1/mediaItems`\n\nThe URL uses [gRPC Transcoding](https://github.com/googleapis/googleapis/blob/master/google/api/http.proto) syntax.\n\n### Query parameters\n\n|Parameters|||\n|-|-|-\n|`pageSize`|`integer`|Maximum number of media items to return in the response. Fewer media items might be returned than the specified number. The default `pageSize` i[...]",
        "operationId": "ListItems"
      }
    },
    "/v1/mediaItems/%7B%7BmediaItemId%7D%7D": {},
    "/v1/mediaItems/%7B%7BmediaItem.id%7D%7D": {},
    "/v1/mediaItems:search": {},
    "/v1/mediaItems:batchGet": {
      "get": {
        "summary": "Create Media Item(s) in Google photo library",
        "description": "\nReturns the list of media items for the specified media item identifiers. Items are returned in the same order as the supplied identifiers.\n\n### HTTP request\n\n`GET https://photoslibrary.googleapis.com/v1/mediaItems:batchGet`\n\nThe URL uses [gRPC Transcoding](https://github.com/googleapis/googleapis/blob/master/google/api/http.proto) syntax.\n\n### Query parameters\n\n|Parameters|||\n|-|-|-\n|`mediaItemIds`|`string`|Identifiers of the media items to be requested. Mu[...]",
        "operationId": "CreateItems"
      }
    },
    "/v1/mediaItems:batchCreate": {},
    "/v1/sharedAlbums": {
      "get": {
        "summary": "List All Shared Albums",
        "description": "\n\nLists all shared albums available in the Sharing tab of the user's Google Photos app.\n\n### HTTP request\n\n`GET https://photoslibrary.googleapis.com/v1/sharedAlbums`\n\nThe URL uses [gRPC Transcoding](https://github.com/googleapis/googleapis/blob/master/google/api/http.proto) syntax.\n\n### Query parameters\n\n|Parameters|||\n|-|-|-\n|`pageSize`|`integer`|Maximum number of albums to return in the response. Fewer albums might be returned than the specified number. Th[...]",
        "operationId": "ListSharedAlbums"
      }
    },
    "/v1/sharedAlbums/%7B%7BshareToken%7D%7D": {},
    "/v1/sharedAlbums:join": {},
    "/v1/sharedAlbums:leave": {}
  },
  "securityDefinitions": {
    "undefined": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "tokenUrl": "https://oauth2.googleapis.com/token",
      "scopes": {
        "https://www.googleapis.com/auth/photoslibrary https://www.googleapis.com/auth/photoslibrary.edit.appcreateddata https://www.googleapis.com/auth/photoslibrary.sharing https://www.googleapis.com/auth/photoslibrary.edit.appcreateddata": "https://www.googleapis.com/auth/photoslibrary https://www.googleapis.com/auth/photoslibrary.edit.appcreateddata https://www.googleapis.com/auth/photoslibrary.sharing https://www.googleapis.com/auth/photoslibrary.edit.appcreateddata"
      }
    }
  },
  "security": [
    {
      "undefined": [
        "https://www.googleapis.com/auth/photoslibrary https://www.googleapis.com/auth/photoslibrary.edit.appcreateddata https://www.googleapis.com/auth/photoslibrary.sharing https://www.googleapis.com/auth/photoslibrary.edit.appcreateddata"
      ]
    }
  ],
  "tags": []
}