{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "Google Photos",
    "description": "Integrate smart, easy-to-use photo and video features into your product and reach hundreds of millions of people who choose Google Photos.",
    "contact": {
      "name": "Julia Muiruri",
      "url": "https://developers.google.com/photos",
      "email": "juliamuiruri@microsoft.com"
    }
  },
  "host": "photoslibrary.googleapis.com",
  "basePath": "/",
  "schemes": [
    "https"
  ],
  "paths": {
    "/v1/albums": {
      "get": {
        "summary": "List Albums",
        "description": "Lists all user albums.",
        "operationId": "ListAlbums"
      },
      "post": {
        "summary": "Create New Album",
        "description": "Creates an album in a user's Google Photos library.",
        "operationId": "CreateAlbum"
      }
    },
    "/v1/mediaItems": {
      "get": {
        "summary": "List Media Items",
        "description": "List media items from a user's Google Photos library.",
        "operationId": "ListItems"
      }
    },
    "/v1/mediaItems:batchGet": {
      "get": {
        "summary": "Create Media Item(s)",
        "description": "Returns the list of media items.",
        "operationId": "CreateItems"
      }
    },
    "/v1/sharedAlbums": {
      "get": {
        "summary": "List All Shared Albums",
        "description": "Lists all shared albums available",
        "operationId": "ListSharedAlbums"
      }
    }
  },
  "securityDefinitions": {
    "undefined": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "tokenUrl": "https://oauth2.googleapis.com/token",
      "scopes": {
        "https://www.googleapis.com/auth/photoslibrary https://www.googleapis.com/auth/photoslibrary.edit.appcreateddata https://www.googleapis.com/auth/photoslibrary.sharing https://www.googleapis.com/auth/photoslibrary.edit.appcreateddata": "https://www.googleapis.com/auth/photoslibrary https://www.googleapis.com/auth/photoslibrary.edit.appcreateddata https://www.googleapis.com/auth/photoslibrary.sharing https://www.googleapis.com/auth/photoslibrary.edit.appcreateddata"
      }
    }
  },
  "security": [
    {
      "undefined": [
        "https://www.googleapis.com/auth/photoslibrary https://www.googleapis.com/auth/photoslibrary.edit.appcreateddata https://www.googleapis.com/auth/photoslibrary.sharing https://www.googleapis.com/auth/photoslibrary.edit.appcreateddata"
      ]
    }
  ],
  "tags": []
}