{
  "swagger": "2.0",
  "info": {
    "title": "Default title",
    "description": "HubSpot\u2019s CRM is a system for managing customer relationships and storing data. The CRM custom connector provides access to CRM objects or groups of objects, which are represented as a map of property names to values.",
    "version": "1.0",
    "contact": {
      "name": "Troy Taylor",
      "email": "ttaylor@hitachisolutions.com"
    }
  },
  "host": "api.hubapi.com",
  "basePath": "/",
  "schemes": [
    "https"
  ],
  "paths": {
    "/crm/v3/objects/companies": {
      "get": {
        "summary": "List companies",
        "description": "Return a list of companies.",
        "operationId": "CompaniesList"
      },
      "post": {
        "summary": "Create a company",
        "description": "Create a company with the given properties and return a copy of the object, including the ID.",
        "operationId": "CompaniesCreate"
      }
    },
    "/crm/v3/objects/companies/{companyId}": {
      "get": {
        "summary": "Get a company",
        "description": "Read a company identified by {companyId}.",
        "operationId": "CompaniesRead"
      },
      "delete": {
        "summary": "Delete a company",
        "description": "Move a company identified by {companyId} to the recycling bin.",
        "operationId": "CompaniesArchive"
      },
      "patch": {
        "summary": "Update a company",
        "description": "Perform a partial update of a company identified by {companyId}. Provided property values will be overwritten. Read-only and non-existent properties will be ignored. Properties values can be cleared by passing an empty string.",
        "operationId": "CompaniesUpdate"
      }
    },
    "/crm/v3/objects/contacts": {
      "get": {
        "summary": "List contacts",
        "description": "Read a list of contacts.",
        "operationId": "ContactsList"
      },
      "post": {
        "summary": "Create a contact",
        "description": "Create a contact with the given properties and return a copy of the object, including the ID.",
        "operationId": "ContactsCreate"
      }
    },
    "/crm/v3/objects/contacts/{contactId}": {
      "get": {
        "summary": "Get a contact",
        "description": "Read a contact identified by {contactId}.",
        "operationId": "ContactsRead"
      },
      "delete": {
        "summary": "Delete a contact",
        "description": "Move a contact identified by {contactId} to the recycling bin.",
        "operationId": "ContactsArchive"
      },
      "patch": {
        "summary": "Update a contact",
        "description": "Perform a partial update of a contact identified by {contactId}. Provided property values will be overwritten. Read-only and non-existent properties will be ignored. Properties values can be cleared by passing an empty string.",
        "operationId": "ContactsUpdate"
      }
    },
    "/crm/v3/objects/deals": {
      "get": {
        "summary": "List deals",
        "description": "Return a list of deals",
        "operationId": "DealsList"
      },
      "post": {
        "summary": "Create a deal",
        "description": "Create a deal with the given properties and return a copy of the object, including the ID.",
        "operationId": "DealsCreate"
      }
    },
    "/crm/v3/objects/deals/{dealId}": {
      "get": {
        "summary": "Get a deal",
        "description": "Read a deal identified by {dealId}.",
        "operationId": "DealsRead"
      },
      "delete": {
        "summary": "Delete a deal",
        "description": "Move a deal identified by {dealId} to the recycling bin.",
        "operationId": "DealsArchive"
      },
      "patch": {
        "summary": "Update a deal",
        "description": "Perform a partial update of a deal identified by {dealId}. Provided property values will be overwritten. Read-only and non-existent properties will be ignored. Properties values can be cleared by passing an empty string.",
        "operationId": "DealsUpdate"
      }
    },
    "/crm/v3/objects/products": {
      "get": {
        "summary": "List products",
        "description": "Return a list of products",
        "operationId": "ProductsList"
      },
      "post": {
        "summary": "Create a product",
        "description": "Create a product with the given properties and return a copy of the object, including the ID.",
        "operationId": "ProductsCreate"
      }
    },
    "/crm/v3/objects/products/{productId}": {
      "get": {
        "summary": "Get a product",
        "description": "Read a product identified by {productId}.",
        "operationId": "ProductsRead"
      },
      "delete": {
        "summary": "Delete a product",
        "description": "Move a product identified by {productId} to the recycling bin.",
        "operationId": "ProductsArchive"
      },
      "patch": {
        "summary": "Update a product",
        "description": "Perform a partial update of a product identified by {productId}. Provided property values will be overwritten. Read-only and non-existent properties will be ignored. Properties values can be cleared by passing an empty string.",
        "operationId": "ProductsUpdate"
      }
    },
    "/crm/v3/owners/": {
      "get": {
        "summary": "List owners",
        "operationId": "OwnersList",
        "description": "Get a page of owners"
      }
    },
    "/crm/v3/owners/{ownerId}": {
      "get": {
        "summary": "Get an owner",
        "description": "Read an owner by given id or userId",
        "operationId": "OwnersRead"
      }
    },
    "/crm/v3/pipelines/{objectType}": {
      "get": {
        "summary": "List pipelines",
        "description": "Return all pipelines for the object type specified by {objectType}.",
        "operationId": "PipelinesList"
      },
      "post": {
        "summary": "Create a pipeline",
        "description": "Create a new pipeline with the provided property values. The entire pipeline object, including its unique ID, will be returned in the response.",
        "operationId": "PipelinesCreate"
      }
    },
    "/crm/v3/pipelines/{objectType}/{pipelineId}": {
      "get": {
        "summary": "Get a pipeline",
        "description": "Return a single pipeline object identified by its unique {pipelineId}.",
        "operationId": "PipelinesRead"
      },
      "delete": {
        "summary": "Delete a pipeline",
        "description": "Archive the pipeline identified by {pipelineId}.",
        "operationId": "PipelinesArchive"
      },
      "put": {
        "summary": "Replace a pipeline",
        "description": "Replace all the properties of an existing pipeline with the values provided. This will overwrite any existing pipeline stages. The updated pipeline will be returned in the response.",
        "operationId": "PipelinesReplace"
      },
      "patch": {
        "summary": "Update a pipeline",
        "description": "Perform a partial update of the pipeline identified by {pipelineId}. The updated pipeline will be returned in the response.",
        "operationId": "PipelinesUpdate"
      }
    },
    "/crm/v3/pipelines/{objectType}/{pipelineId}/stages": {
      "post": {
        "summary": "Create a pipeline stage",
        "description": "Create a new stage associated with the pipeline identified by {pipelineId}. The entire stage object, including its unique ID, will be returned in the response.",
        "operationId": "PipelinesCreateStage"
      }
    },
    "/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}": {
      "get": {
        "summary": "Get a pipeline stage",
        "description": "Return the stage identified by {stageId} associated with the pipeline identified by {pipelineId}.",
        "operationId": "PipelinesReadStage"
      },
      "delete": {
        "summary": "Delete a pipeline stage",
        "description": "Archive the pipeline stage identified by {stageId} associated with the pipeline identified by {pipelineId}.",
        "operationId": "PipelinesArchiveStage"
      },
      "put": {
        "summary": "Replace a pipeline stage",
        "description": "Replace all the properties of an existing pipeline stage with the values provided. The updated stage will be returned in the response.",
        "operationId": "PipelinesReplaceStage"
      },
      "patch": {
        "summary": "Update a pipeline stage",
        "description": "Perform a partial update of the pipeline stage identified by {stageId} associated with the pipeline identified by {pipelineId}. Any properties not included in this update will keep their existing values. The updated stage will be returned in the response.",
        "operationId": "PipelinesUpdateStage"
      }
    },
    "/crm/v3/properties/{objectType}": {
      "get": {
        "summary": "List properties",
        "description": "Read all existing properties for the specified object type and HubSpot account.",
        "operationId": "PropertiesList"
      },
      "post": {
        "summary": "Create a property",
        "description": "Create and return a copy of a new property for the specified object type.",
        "operationId": "PropertiesCreate"
      }
    },
    "/crm/v3/properties/{objectType}/{propertyName}": {
      "get": {
        "summary": "Get a property",
        "description": "Read a property identified by {propertyName}.",
        "operationId": "PropertiesRead"
      },
      "delete": {
        "summary": "Delete a property",
        "description": "Move a property identified by {propertyName} to the recycling bin.",
        "operationId": "PropertiesArchive"
      },
      "patch": {
        "summary": "Update a property",
        "description": "Perform a partial update of a property identified by {propertyName}. Provided fields will be overwritten.",
        "operationId": "PropertiesUpdate"
      }
    },
    "/crm/v3/objects/line_items": {
      "get": {
        "summary": "List line items",
        "description": "Return a list of line items. Control what is returned via the properties query param.",
        "operationId": "LineItemsList"
      },
      "post": {
        "summary": "Create a line item",
        "description": "Create a line item with the given properties and return a copy of the object, including the ID.",
        "operationId": "LineItemsCreate"
      }
    },
    "/crm/v3/objects/line_items/{lineItemId}": {
      "get": {
        "summary": "Get a line item",
        "description": "Read a lite item identified by {lineItemId}. {lineItemId} refers to the internal object ID by default, or optionally any unique property value as specified by the idProperty query param. Control what is returned via the properties query param.",
        "operationId": "LineItemsRead"
      },
      "delete": {
        "summary": "Delete a line item",
        "description": "Move an Object identified by {lineItemId} to the recycling bin.",
        "operationId": "LineItemsArchive"
      },
      "patch": {
        "summary": "Update a line item",
        "description": "Perform a partial update of a line item identified by {lineItemId}. {lineItemId} refers to the internal object ID by default, or optionally any unique property value as specified by the idProperty query param. Provided property values will be overwritten. Read-only and non-existent properties will be ignored. Properties values can be cleared by passing an empty string.",
        "operationId": "LineItemsUpdate"
      }
    },
    "/crm/v3/objects/tickets": {
      "get": {
        "summary": "List tickets",
        "description": "Read a page of tickets. Control what is returned via the properties query param.",
        "operationId": "TicketsList"
      },
      "post": {
        "summary": "Create a ticket",
        "description": "Create a ticket with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard tickets is provided.",
        "operationId": "TicketsCreate"
      }
    },
    "/crm/v3/objects/tickets/{ticketId}": {
      "get": {
        "summary": "Get a ticket",
        "description": "Read a ticket identified by {ticketId}. {ticketId} refers to the internal object ID by default, or optionally any unique property value as specified by the idProperty query param. Control what is returned via the properties query param.",
        "operationId": "TicketsRead"
      },
      "delete": {
        "summary": "Delete a ticket",
        "description": "Move a ticket identified by {ticketId} to the recycling bin.",
        "operationId": "TicketsArchive"
      },
      "patch": {
        "operationId": "TicketsUpdate",
        "summary": "Update a ticket",
        "description": "Perform a partial update of a ticket identified by {ticketId}. {ticketId} refers to the internal object ID by default, or optionally any unique property value as specified by the idProperty query param. Provided property values will be overwritten. Read-only and non-existent properties will be ignored. Properties values can be cleared by passing an empty string."
      }
    },
    "/crm/v3/objects/companies/search": {
      "post": {
        "summary": "Search companies",
        "operationId": "SearchCompanies",
        "description": "The CRM search endpoints make getting data more efficient by allowing developers to filter, sort, and search across any CRM object type."
      }
    },
    "/crm/v3/objects/contacts/search": {
      "post": {
        "summary": "Search contacts",
        "operationId": "SearchContacts",
        "description": "The CRM search endpoints make getting data more efficient by allowing developers to filter, sort, and search across any CRM object type."
      }
    },
    "/crm/v3/objects/deals/search": {
      "post": {
        "summary": "Search deals",
        "operationId": "SearchDeals",
        "description": "The CRM search endpoints make getting data more efficient by allowing developers to filter, sort, and search across any CRM object type."
      }
    },
    "/crm/v3/objects/products/search": {
      "post": {
        "summary": "Search products",
        "operationId": "SearchProducts",
        "description": "The CRM search endpoints make getting data more efficient by allowing developers to filter, sort, and search across any CRM object type."
      }
    },
    "/crm/v3/objects/tickets/search": {
      "post": {
        "summary": "Search tickets",
        "operationId": "SearchTickets",
        "description": "The CRM search endpoints make getting data more efficient by allowing developers to filter, sort, and search across any CRM object type."
      }
    },
    "/crm/v3/objects/line_items/search": {
      "post": {
        "summary": "Search line items",
        "operationId": "SearchLineItems",
        "description": "The CRM search endpoints make getting data more efficient by allowing developers to filter, sort, and search across any CRM object type."
      }
    },
    "/crm/v3/objects/quotes/search": {
      "post": {
        "summary": "Search quotes",
        "operationId": "SearchQuotes",
        "description": "The CRM search endpoints make getting data more efficient by allowing developers to filter, sort, and search across any CRM object type."
      }
    },
    "/crm/v3/objects/custom_objects/search": {
      "post": {
        "summary": "Search custom objects",
        "operationId": "SearchCustomObjects",
        "description": "The CRM search endpoints make getting data more efficient by allowing developers to filter, sort, and search across any CRM object type."
      }
    }
  },
  "securityDefinitions": {
    "oauth2_auth": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
      "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
      "scopes": {
        "crm.objects.marketing_events.read contacts content reports actions timeline oauth forms files crm.objects.marketing_events.write crm.schemas.custom.read crm.objects.custom.read crm.objects.feedback_submissions.read crm.objects.custom.write": "crm.objects.marketing_events.read contacts content reports actions timeline oauth forms files crm.objects.marketing_events.write crm.schemas.custom.read crm.objects.custom.read crm.objects.feedback_submissions.read crm.objects.custom.write"
      }
    }
  },
  "security": [
    {
      "oauth2_auth": [
        "crm.objects.marketing_events.read contacts content reports actions timeline oauth forms files crm.objects.marketing_events.write crm.schemas.custom.read crm.objects.custom.read crm.objects.feedback_submissions.read crm.objects.custom.write"
      ]
    }
  ],
  "tags": []
}
