{
  "swagger": "2.0",
  "info": {
    "version": "0.3.0",
    "title": "NetDocuments",
    "description": "NetDocuments is a cloud content management service for businesses of all sizes to securely create, store, manage and share their document work anywhere, anytime."
  },
  "host": "api.vault.netvoyage.com",
  "basePath": "/",
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "oauth2_auth": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://vault.netvoyage.com/neWeb2/OAuth.aspx",
      "tokenUrl": "https://api.vault.netvoyage.com/v1/OAuth",
      "scopes": {
        "read": "read data",
        "organize": "create folders, file to folders, change acls or profile, etc",
        "edit": "edit",
        "delete_doc": "delete_doc",
        "delete_container": "delete_container",
        "lookup": "modify lookup tables",
        "admin": "modify user groups"
      }
    }
  },
  "security": [
    {
      "oauth2_auth": [
        "read",
        "organize",
        "edit",
        "delete_doc",
        "lookup"
      ]
    }
  ],
  "paths": {
    "/v1/User/{id}/info": {
      "get": {
        "summary": "Get user info",
        "operationId": "GetUserInfo",
        "description": "Get information about a user",
        "security": [
          {
            "nd_auth": [
              "read"
            ]
          }
        ]
      }
    },
    "/v1/User/cabinets": {
      "get": {
        "summary": "Get list of user cabinets",
        "operationId": "GetUserCabinets",
        "description": "Get User cabinets",
        "security": [
          {
            "nd_auth": [
              "read"
            ]
          }
        ]
      }
    },
    "/v1/Document/{id}/new": {
      "put": {
        "summary": "Create a new version of a document",
        "description": "Create new version of a document",
        "operationId": "NewVersion",
        "security": [
          {
            "nd_auth": [
              "edit"
            ]
          }
        ]
      }
    },
    "/v1/Document/{id}/info": {
      "get": {
        "summary": "Get document profile",
        "description": "Get information about a document",
        "operationId": "GetDocInfo",
        "security": [
          {
            "nd_auth": [
              "read"
            ]
          }
        ]
      },
      "put": {
        "summary": "Rename document",
        "description": "Rename a document",
        "operationId": "RenameDocument",
        "security": [
          {
            "nd_auth": [
              "edit"
            ]
          }
        ]
      }
    },
    "/v1/Document/{id}": {
      "get": {
        "summary": "Get document content",
        "operationId": "GetDocContent",
        "description": "Retrieve a document",
        "security": [
          {
            "nd_auth": [
              "read"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete document",
        "operationId": "DeleteDoc",
        "security": [
          {
            "nd_auth": [
              "delete_doc"
            ]
          }
        ],
        "description": "Delete a document"
      },
      "put": {
        "summary": "Update document",
        "operationId": "UpdateDocument",
        "security": [
          {
            "nd_auth": [
              "edit"
            ]
          }
        ],
        "description": "Update the content of a document"
      }
    },
    "/v1/Folder": {
      "post": {
        "summary": "Create folder",
        "operationId": "CreateFolder",
        "security": [
          {
            "nd_auth": [
              "organize"
            ]
          }
        ],
        "description": "Create a new folder"
      }
    },
    "/v1/Folder/{id}": {
      "get": {
        "summary": "Get folder items",
        "operationId": "GetFldContent",
        "security": [
          {
            "nd_auth": [
              "read"
            ]
          }
        ],
        "description": "Retrieve the contents of a folder, including documents and subfolders"
      },
      "post": {
        "summary": "File or unfile document to folder",
        "description": "File an item in a folder or unfile an item from a folder.",
        "operationId": "FileFolder",
        "security": [
          {
            "nd_auth": [
              "organize"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete folder",
        "operationId": "DeleteFolder",
        "security": [
          {
            "nd_auth": [
              "delete_container"
            ]
          }
        ],
        "description": "Delete a folder"
      }
    },
    "/v1/Folder/{id}/info": {
      "put": {
        "summary": "Rename folder",
        "description": "Rename a folder",
        "operationId": "RenameFolder",
        "security": [
          {
            "nd_auth": [
              "edit"
            ]
          }
        ]
      }
    },
    "/v1/Folder/{id}/follow": {
      "post": {
        "summary": "Follow folder",
        "operationId": "FollowFolder",
        "security": [
          {
            "nd_auth": [
              "organize"
            ]
          }
        ],
        "description": "Receive alerts when new content is added to a folder"
      }
    },
    "/v1/Document/follow": {
      "post": {
        "summary": "Follow document",
        "description": "Receive alerts when the document is updated",
        "operationId": "FollowDocument",
        "security": [
          {
            "nd_auth": [
              "organize"
            ]
          }
        ]
      }
    },
    "/v1/Search/{cabId}": {
      "get": {
        "summary": "Search cabinet",
        "operationId": "SearchCab",
        "security": [
          {
            "nd_auth": [
              "read"
            ]
          }
        ],
        "description": "Search the specified cabinet"
      }
    },
    "/v1/User/info": {
      "get": {
        "summary": "Get current user info",
        "description": "Get info about current user, ID isn't required",
        "operationId": "GetCurrentUserInfo",
        "security": [
          {
            "nd_auth": [
              "read"
            ]
          }
        ]
      }
    },
    "/v1/Document/checkin": {
      "post": {
        "summary": "Check in document",
        "operationId": "CheckinDoc",
        "description": "Check in a checked-out document",
        "security": [
          {
            "nd_auth": [
              "edit"
            ]
          }
        ]
      }
    },
    "/v1/Document/checkout": {
      "post": {
        "summary": "Check out document",
        "operationId": "CheckOutDoc",
        "security": [
          {
            "nd_auth": [
              "edit"
            ]
          }
        ],
        "description": "Check out a document"
      }
    },
    "/v1/Document/upload": {
      "post": {
        "summary": "Create document",
        "operationId": "CreateDocument",
        "security": [
          {
            "nd_auth": [
              "edit"
            ]
          }
        ],
        "description": "Create a new document"
      }
    },
    "/v1/Document/lock": {
      "post": {
        "summary": "Lock document version",
        "operationId": "LockDocumentVersion",
        "description": "Lock document version",
        "security": [
          {
            "nd_auth": [
              "edit"
            ]
          }
        ]
      }
    },
    "/v1/Document/{documentID}/versionList": {
      "get": {
        "summary": "Get document versions",
        "operationId": "GetDocumentVersions",
        "description": "Get document versions",
        "security": [
          {
            "nd_auth": [
              "read"
            ]
          }
        ]
      }
    },
    "/v1/Document/createsecuredlink": {
      "post": {
        "summary": "Create secured link",
        "operationId": "CreateSecuredLink",
        "security": [
          {
            "nd_auth": [
              "edit"
            ]
          }
        ],
        "description": "Generate a link to a document that can be accessed by anyone"
      }
    },
    "/v1/Document/{id}/history": {
      "get": {
        "summary": "Document history",
        "operationId": "GetDocHistory",
        "security": [
          {
            "nd_auth": [
              "read"
            ]
          }
        ],
        "description": "Retrieve a list of actions taken on a document"
      }
    },
    "/v1/Workspace/{cabinetID}/{parentID}/{childID}/info": {
      "get": {
        "summary": "Get or create a workspace (with parent and child attributes)",
        "description": "Get or create a workspace (with parent and child attributes)",
        "operationId": "CreateWorkspaceParentChild",
        "security": [
          {
            "nd_auth": [
              "read"
            ]
          }
        ]
      }
    },
    "/v1/Workspace/{cabinetID}/{parentID}/info": {
      "get": {
        "summary": "Get or create a workspace (with a single attribute)",
        "description": "Get or create a workspace (with a single attribute)",
        "operationId": "CreateWorkspaceSingle",
        "security": [
          {
            "nd_auth": [
              "read"
            ]
          }
        ]
      }
    },
    "/v1/Workspace/{workspaceID}/info": {
      "get": {
        "summary": "Get workspace information",
        "description": "Get workspace information",
        "operationId": "GetWorkspaceInformation",
        "security": [
          {
            "nd_auth": [
              "read"
            ]
          }
        ]
      }
    },
    "/v1/attributes/{repositoryID}/{childAttributeID}/{parentID}/{childID}": {
      "put": {
        "summary": "Create or update a child lookup table entry",
        "description": "Create or update a child lookup table entry",
        "operationId": "CreateChildEntry",
        "security": [
          {
            "nd_auth": [
              "lookup"
            ]
          }
        ]
      },
      "get": {
        "summary": "Get a child lookup table entry",
        "description": "Get a child lookup table entry",
        "operationId": "GetChildEntry",
        "security": [
          {
            "nd_auth": [
              "read"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete a child lookup table entry",
        "description": "Delete a child lookup table entry",
        "operationId": "DeleteChildEntry",
        "security": [
          {
            "nd_auth": [
              "lookup"
            ]
          }
        ]
      }
    },
    "/v1/attributes/{repositoryID}/{attributeID}/{parentID}": {
      "put": {
        "summary": "Create or update a lookup table entry",
        "description": "Create or update a lookup table entry",
        "operationId": "CreateEntry",
        "security": [
          {
            "nd_auth": [
              "lookup"
            ]
          }
        ]
      },
      "get": {
        "summary": "Get a lookup table entry or search for child table entries",
        "description": "Get a lookup table entry or search for child table entries",
        "operationId": "GetLookupEntry",
        "security": [
          {
            "nd_auth": [
              "read"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete a lookup table entry",
        "description": "Delete a lookup table entry",
        "operationId": "DeleteLookupEntry",
        "security": [
          {
            "nd_auth": [
              "lookup"
            ]
          }
        ]
      }
    },
    "/v1/attributes/{repositoryID}/{attributeID}": {
      "get": {
        "summary": "Search for lookup table entries",
        "description": "Search for lookup table entries",
        "operationId": "SearchLookupEntries",
        "security": [
          {
            "nd_auth": [
              "read"
            ]
          }
        ]
      }
    },
    "/v2/Search": {
      "get": {
        "summary": "Search one or more cabinets",
        "description": "Search one or more cabinets",
        "operationId": "SearchCabinets",
        "security": [
          {
            "nd_auth": [
              "read"
            ]
          }
        ]
      }
    },
    "/v1/Workspace/{workspaceID}": {
      "post": {
        "summary": "Refresh a workspace",
        "description": "Refresh a workspace",
        "operationId": "RefreshWorkspace",
        "security": [
          {
            "nd_auth": [
              "organize"
            ]
          }
        ]
      }
    },
    "/v2/document/{id}/lock": {
      "post": {
        "summary": "Lock document",
        "description": "Lock document",
        "operationId": "LockDocument",
        "security": [
          {
            "nd_auth": [
              "edit"
            ]
          }
        ]
      }
    },
    "/v2/document/{id}/unlock": {
      "post": {
        "summary": "Unlock document",
        "description": "Unock document",
        "operationId": "UnockDocument",
        "security": [
          {
            "nd_auth": [
              "edit"
            ]
          }
        ]
      }
    },
    "/v1/Repository/{repositoryID}/log": {
      "get": {
        "summary": "Get repository log",
        "description": "Get repository log",
        "operationId": "GetRepositoryLog",
        "security": [
          {
            "nd_auth": [
              "read"
            ]
          }
        ]
      }
    },
    "/v1/Repository/{repositoryID}/info": {
      "get": {
        "summary": "Get repository information",
        "description": "Get repository information",
        "operationId": "GetRepositoryInformation",
        "security": [
          {
            "nd_auth": [
              "read"
            ]
          }
        ]
      }
    },
    "/v1/Repository/{repositoryID}/users": {
      "get": {
        "summary": "Get repository users",
        "description": "Get repository users",
        "operationId": "GetRepositoryUsers",
        "security": [
          {
            "nd_auth": [
              "read"
            ]
          }
        ]
      }
    },
    "/v1/Repository/{repositoryID}/groups": {
      "get": {
        "summary": "Get repository groups",
        "description": "Get repository groups",
        "operationId": "GetRepositoryGroups",
        "security": [
          {
            "nd_auth": [
              "read"
            ]
          }
        ]
      }
    },
    "/v1/Repository/{repositoryID}/group": {
      "post": {
        "summary": "Create repository group",
        "operationId": "CreateRepositoryGroup",
        "description": "Create a repository group",
        "security": [
          {
            "nd_auth": [
              "admin"
            ]
          }
        ]
      }
    },
    "/v1/Repository/{repositoryID}/group/{groupID}": {
      "delete": {
        "summary": "Delete repository group",
        "operationId": "DeleteRepositoryGroup",
        "description": "Delete a repository group",
        "security": [
          {
            "nd_auth": [
              "admin"
            ]
          }
        ]
      }
    },
    "/v1/User": {
      "post": {
        "summary": "Create user",
        "operationId": "CreateUser",
        "description": "Create a user in a repository",
        "security": [
          {
            "nd_auth": [
              "admin"
            ]
          }
        ]
      }
    },
    "/v1/Repository/{repositoryID}/members": {
      "post": {
        "summary": "Add user to or remove user from repository",
        "operationId": "AddOrRemoveUserRepository",
        "description": "Add user to or remove user from repository",
        "security": [
          {
            "nd_auth": [
              "admin"
            ]
          }
        ]
      }
    },
    "/v2/container/{workspaceID}/collabspace": {
      "post": {
        "summary": "Create CollabSpace",
        "operationId": "CreateCollabSpace",
        "description": "Create a new CollabSpace",
        "security": [
          {
            "nd_auth": [
              "organize"
            ]
          }
        ]
      }
    },
    "/v1/cabinet/{cabinetID}/settings": {
      "get": {
        "summary": "Get cabinet settings",
        "description": "Get cabinet settings",
        "operationId": "GetCabinetSettings",
        "security": [
          {
            "nd_auth": [
              "read"
            ]
          }
        ]
      }
    },
    "/v1/cabinet/{cabinetID}/info": {
      "get": {
        "summary": "Get cabinet information",
        "description": "Get cabinet information",
        "operationId": "GetCabinetInformation",
        "security": [
          {
            "nd_auth": [
              "read"
            ]
          }
        ]
      }
    },
    "/v1/cabinet/{cabinetID}/customAttributes": {
      "get": {
        "summary": "Get cabinet custom attributes",
        "description": "Get cabinet custom attributes",
        "operationId": "GetCabinetCustomAttributes",
        "security": [
          {
            "nd_auth": [
              "read"
            ]
          }
        ]
      }
    },
    "/v1/cabinet/{cabinetID}/membership": {
      "get": {
        "summary": "Get unhidden cabinet groups access rights",
        "description": "Get unhidden cabinet groups access rights",
        "operationId": "GetCabinetDefaultAccess",
        "security": [
          {
            "nd_auth": [
              "read"
            ]
          }
        ]
      },
      "post": {
        "summary": "Add to or remove group from cabinet",
        "description": "Add group to cabinet and default access rights",
        "operationId": "AddToOrRemoveGroupFromCabinet",
        "security": [
          {
            "nd_auth": [
              "admin"
            ]
          }
        ]
      }
    },
    "/v2/cabinet/{cabinetID}/groups": {
      "get": {
        "summary": "Get cabinet groups",
        "description": "Get all of the groups added to a cabinet",
        "operationId": "GetCabinetGroups",
        "security": [
          {
            "nd_auth": [
              "read"
            ]
          }
        ]
      }
    },
    "/v2/cabinet/{cabinetID}/group/external": {
      "post": {
        "summary": "Create a cabinet external group",
        "description": "Create a cabinet external group",
        "operationId": "CreateCabinetExternalGroup",
        "security": [
          {
            "nd_auth": [
              "admin"
            ]
          }
        ]
      }
    },
    "/v1/Search/{cabinetID}": {
      "post": {
        "summary": "Search a cabinet and modify ACLs",
        "description": "Search a cabinet and modify ACLs",
        "operationId": "SearchCabinetModifyACLs",
        "security": [
          {
            "nd_auth": [
              "organize"
            ]
          }
        ]
      }
    },
    "/v2/container/{containerID}": {
      "get": {
        "summary": "Get container contents",
        "description": "Get the contents of the selected container",
        "operationId": "GetContainerContents",
        "security": [
          {
            "nd_auth": [
              "read"
            ]
          }
        ]
      }
    },
    "/v1/Group/{groupID}/info": {
      "get": {
        "summary": "Get group information",
        "description": "Get group information",
        "operationId": "GetGroupInformation",
        "security": [
          {
            "nd_auth": [
              "read"
            ]
          }
        ]
      }
    },
    "/v1/Group/{groupID}/members": {
      "get": {
        "summary": "Get group membership",
        "description": "Get group membership",
        "operationId": "GetGroupMembership",
        "security": [
          {
            "nd_auth": [
              "read"
            ]
          }
        ]
      },
      "post": {
        "summary": "Add or remove group member",
        "description": "Add or remove group member",
        "operationId": "AddOrRemoveGroupMember",
        "security": [
          {
            "nd_auth": [
              "admin"
            ]
          }
        ]
      }
    }
  },
  "tags": []
}
