pool:
  vmImage: 'windows-latest'

steps:
- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'
- task: SdtReport@1
  inputs:
    AllTools: false
    APIScan: true
    BinSkim: false
    CodesignValidation: false
    CredScan: true
    FortifySCA: false
    FxCop: false
    ModernCop: false
    MSRD: false
    PoliCheck: true
    PoliCheckBreakOn: 'Severity1'
    RoslynAnalyzers: false
    SDLNativeRules: false
    Semmle: false
    TSLint: true
    TSLintBreakOn: 'Error'
    ToolLogsNotFoundAction: 'Standard'
- task: TSAUpload@1
  inputs:
    tsaVersion: 'TsaV2'
    codebase: 'Existing'
    tsaEnvironment: 'PROD'
    codeBaseName: $(tsacodebasename)
    uploadAPIScan: true
    uploadBinSkim: false
    uploadCredScan: true
    uploadFortifySCA: false
    uploadFxCop: false
    uploadModernCop: false
    uploadPoliCheck: true
    uploadPREfast: false
    uploadRoslyn: false
    uploadTSLint: true
    uploadAsync: true
- task: PublishSecurityAnalysisLogs@3
  inputs:
    ArtifactName: 'CodeAnalysisLogs'
    ArtifactType: 'Container'
- task: PostAnalysis@1
  inputs:
    AllTools: false
    APIScan: true
    BinSkim: false
    CodesignValidation: false
    CredScan: true
    FortifySCA: false
    FxCop: false
    ModernCop: false
    PoliCheck: true
    PoliCheckBreakOn: 'Severity1'
    RoslynAnalyzers: false
    SDLNativeRules: false
    Semmle: false
    TSLint: true
    TSLintBreakOn: 'Error'
    ToolLogsNotFoundAction: 'Standard'
