{
  "swagger": "2.0",
  "info": {
    "title": "HubSpot Marketing",
    "description": "HubSpot Marketing community connector.",
    "version": "1.0",
    "contact": {
      "name": "Troy Taylor",
      "url": "https://www.hitachisolutions.com",
      "email": "ttaylor@hitachisolutions.com"
    }
  },
  "host": "api.hubapi.com",
  "basePath": "/",
  "schemes": [
    "https"
  ],
  "paths": {
    "/marketing/v3/forms/": {
      "get": {
        "summary": "List Forms (Preview)",
        "description": "Returns a list of forms based on the search filters. By default, it returns the first 20 hubspot forms.",
        "operationId": "FormsList"
      },
      "post": {
        "summary": "Create a form (Preview)",
        "description": "Add a new HubSpot form.",
        "operationId": "FormsCreate"
      }
    },
    "/marketing/v3/forms/{formId}": {
      "get": {
        "summary": "Get a form (Preview)",
        "description": "Returns a form based on the form ID provided.",
        "operationId": "FormsRead"
      },
      "delete": {
        "operationId": "FormsArchive",
        "summary": "Delete a form (Preview)",
        "description": "Archive a form definition. New submissions will not be accepted and the form definition will be permanently deleted after 3 months."
      },
      "put": {
        "operationId": "FormsUpdate",
        "summary": "Update a form (Preview)",
        "description": "Update all fields of a HubSpot form definition."
      }
    },
    "/marketing/v3/marketing-events-beta/events/{externalEventId}": {
      "get": {
        "operationId": "MarketingEventRead",
        "summary": "Get a marketing event (Preview)",
        "description": "Returns the details of the Marketing Event with the specified id, if one exists."
      },
      "delete": {
        "operationId": "MarketingEventsArchive",
        "summary": "Delete a marketing event (Preview)",
        "description": "Archives an existing Marketing Event with the specified id, if one exists."
      },
      "put": {
        "summary": "Create or update a marketing event (Preview)",
        "description": "Upserts a Marketing Event. If there is an existing Marketing event with the specified id, it will be updated; otherwise a new event will be created.",
        "operationId": "MarketingEventsUpdateCreateOrUpdate"
      }
    },
    "/marketing-emails/v1/emails": {
      "get": {
        "summary": "Get all marketing emails (V1)",
        "description": "Get all marketing emails for a HubSpot account.",
        "operationId": "MarketingEmailsList"
      }
    },
    "/marketing-emails/v1/emails/{id}": {
      "get": {
        "summary": "Get a marketing email (V1)",
        "description": "Get the details for a specific marketing email.",
        "operationId": "MarketingEmailsRead"
      },
      "delete": {
        "summary": "Delete a marketing email (V1)",
        "description": "Archive a marketing email.",
        "operationId": "MarketingEmailsArchive"
      },
      "put": {
        "summary": "Update a marketing email (V1)",
        "description": "Update a marketing email.",
        "operationId": "MarketingEmailsUpdate"
      }
    },
    "/email/public/v1/campaigns/{campaign_id}": {
      "get": {
        "summary": "Get campaign data for a particular campaign (V1)",
        "description": "For a given campaign, return data associated with the campaign.",
        "operationId": "MarketingEmailsCampaignRead"
      }
    },
    "/marketing-emails/v1/emails/": {
      "post": {
        "summary": "Create a marketing email (V1)",
        "description": "Create a new marketing email.",
        "operationId": "MarketingEmailsCreate"
      }
    }
  },
  "securityDefinitions": {
    "oauth2_auth": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
      "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
      "scopes": {
        "forms files hubdb transactional-email settings.users.write conversations.visitor_identification.tokens.create integration-sync tickets e-commerce files.ui_hidden.read crm.objects.marketing_events.read accounting crm.objects.marketing_events.write crm.schemas.custom.read crm.objects.custom.read crm.objects.feedback_submissions.read sales-email-read crm.objects.custom.write forms-uploaded-files settings.users.read crm.import contacts content reports social automation settings.billing.writ[...]"
      }
    }
  },
  "security": [
    {
      "oauth2_auth": [
        "forms files hubdb transactional-email settings.users.write conversations.visitor_identification.tokens.create integration-sync tickets e-commerce files.ui_hidden.read crm.objects.marketing_events.read accounting crm.objects.marketing_events.write crm.schemas.custom.read crm.objects.custom.read crm.objects.feedback_submissions.read sales-email-read crm.objects.custom.write forms-uploaded-files settings.users.read crm.import contacts content reports social automation settings.billing.writ[...]"
      ]
    }
  ],
  "tags": []
}
