{
  "swagger": "2.0",
  "info": {
    "title": "Default title",
    "description": "Xero projects community connector.",
    "version": "1.0",
    "contact": {
      "name": "Troy Taylor",
      "email": "ttaylor@hitachisolutions.com"
    }
  },
  "host": "api.xero.com",
  "basePath": "/projects.xro/2.0/",
  "schemes": [
    "https"
  ],
  "paths": {
    "/Projects/{projectId}": {
      "get": {
        "summary": "Retrieve a project",
        "description": "Allows you to retrieve a project.",
        "operationId": "ProjectGet"
      },
      "put": {
        "summary": "Update a project",
        "operationId": "ProjectsUpdate",
        "description": "Update the project"
      },
      "patch": {
        "summary": "Update a project status",
        "description": "This method updates the status of a project.",
        "operationId": "ProjectsUpdateStatus"
      }
    },
    "/Projects": {
      "get": {
        "summary": "Retrieve projects",
        "description": "Allows you to retrieve multiple projects",
        "operationId": "ProjectsGetMultiple"
      },
      "post": {
        "summary": "Create a project",
        "description": "This method creates a project for the specified contact.",
        "operationId": "ProjectsCreate"
      }
    },
    "/projects/{projectId}/tasks/{taskId}": {
      "get": {
        "summary": "Retrieve a task",
        "description": "Allows you to retrieve a task.",
        "operationId": "TasksGet"
      },
      "put": {
        "summary": "Update a task",
        "description": "This method updates the details of a task.",
        "operationId": "TasksUpdate"
      },
      "delete": {
        "summary": "Delete a task",
        "operationId": "TasksDelete",
        "description": "This method will delete a task. Note that if the task has a service associated or has a status `INVOICED`, it will not be removed."
      }
    },
    "/projects/{projectId}/tasks": {
      "get": {
        "summary": "Retrieve multiple tasks",
        "operationId": "TasksGetMultiple",
        "description": "Allows you to retrieve multiple tasks"
      },
      "post": {
        "summary": "Create a task",
        "description": "This method creates a new task for a given project.",
        "operationId": "TasksCreate"
      }
    }
  },
  "securityDefinitions": {
    "oauth2_auth": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://login.xero.com/identity/connect/authorize",
      "tokenUrl": "https://identity.xero.com/connect/token",
      "scopes": {
        "accounting.transactions accounting.transactions.read accounting.reports.read accounting.reports.tenninetynine.read accounting.journals.read accounting.settings accounting.settings.read accounting.contacts accounting.contacts.read accounting.attachments accounting.attachments.read": "accounting.transactions accounting.transactions.read accounting.reports.read accounting.reports.tenninetynine.read accounting.journals.read accounting.settings accounting.settings.read accounting.contacts ac[...]"
      }
    }
  },
  "security": [
    {
      "oauth2_auth": [
        "accounting.transactions accounting.transactions.read accounting.reports.read accounting.reports.tenninetynine.read accounting.journals.read accounting.settings accounting.settings.read accounting.contacts accounting.contacts.read accounting.attachments accounting.attachments.read"
      ]
    }
  ],
  "tags": []
}
