# Trigger on every push to dev branch
# A push also happens when PR is merged
on:
  push:
    branches:
      - dev

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "microsoft/PowerPlatformConnectors"
        source_branch: "dev"
        destination_branch: "master"
        github_token: ${{ secrets.PAT }}
