# Trigger at the end of every day
on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@3832fe8e2be32372e1b3970bbae8e7079edeec88 # v2.3.0
      with:
        source_repo: "microsoft/PowerPlatformConnectors"
        source_branch: "dev"
        destination_branch: "master"
        github_token: ${{ secrets.SYNC_PAT }}
