{
  "swagger": "2.0",
  "info": {
    "title": "HubSpot CMS",
    "description": "This connector is used to retrieve and make changes to HubSpot CMS. HubSpot CMS is a SaaS CMS designed to help businesses grow their web presence with a special emphasis on enabling marketers. It is designed to be used on business websites where non-technical content creators need to be able to build, measure, and iterate on content independently while working within design, style, and functionality. The content, lead collection, and analytics are also integrated with the Hub[...]",
    "version": "1.0",
    "contact": {
      "name": "Troy Taylor",
      "url": "https://www.hitachisolutions.com",
      "email": "ttaylor@hitachisolutions.com"
    }
  },
  "host": "api.hubapi.com",
  "basePath": "/",
  "schemes": [
    "https"
  ],
  "paths": {
    "/content/api/v2/pages": {
      "get": {
        "summary": "List pages (V2)",
        "description": "Get all of your pages. Supports paging and filtering.",
        "operationId": "PagesList"
      },
      "post": {
        "summary": "Create a new page (V2)",
        "description": "Create a new page.",
        "operationId": "PagesCreate"
      }
    },
    "/content/api/v2/pages/{page_id}": {
      "delete": {
        "summary": "Delete a page (V2)",
        "description": "Marks a page as deleted. Returns 204 No Content letting you know that the page was successfully deleted. The page can be restored later via a POST to the restore-deleted endpoint.",
        "operationId": "PagesArchive"
      },
      "put": {
        "summary": "Update a page (V2)",
        "description": "Updates a page in the database. If not all top level fields are included in the body, we will only update the included fields.",
        "operationId": "PagesUpdate"
      }
    },
    "/content/api/v2/pages/{page_id}/publish-action": {
      "post": {
        "summary": "Publish or unpublish a page (V2)",
        "description": "Either publishes or cancels publishing based on the POSTed JSON.",
        "operationId": "PagesPublish"
      }
    },
    "/content/api/v2/templates": {
      "get": {
        "summary": "List templates (V2)",
        "description": "Get all templates.",
        "operationId": "TemplatesList"
      },
      "post": {
        "summary": "Create a new template (V2)",
        "description": "Create a new coded template object in Design Manager.",
        "operationId": "TemplatesCreate"
      }
    },
    "/content/api/v2/templates/{template_id}": {
      "delete": {
        "summary": "Delete a template (V2)",
        "description": "Marks the selected Template as deleted. The Template can be restored later via a POST to the restore-deleted endpoint.",
        "operationId": "TemplatesArchive"
      },
      "put": {
        "summary": "Update a template (V2)",
        "description": "Updates a template. If not all the fields are included in the body, we will only update the included fields.",
        "operationId": "TemplatesUpdate"
      }
    }
  },
  "securityDefinitions": {
    "oauth2_auth": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
      "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
      "scopes": {
        "forms files hubdb transactional-email settings.users.write conversations.visitor_identification.tokens.create integration-sync tickets e-commerce files.ui_hidden.read crm.objects.marketing_events.read accounting crm.objects.marketing_events.write crm.schemas.custom.read crm.objects.custom.read crm.objects.feedback_submissions.read sales-email-read crm.objects.custom.write forms-uploaded-files settings.users.read crm.import contacts content reports social automation settings.billing.writ[...]"
      }
    }
  },
  "security": [
    {
      "oauth2_auth": [
        "forms files hubdb transactional-email settings.users.write conversations.visitor_identification.tokens.create integration-sync tickets e-commerce files.ui_hidden.read crm.objects.marketing_events.read accounting crm.objects.marketing_events.write crm.schemas.custom.read crm.objects.custom.read crm.objects.feedback_submissions.read sales-email-read crm.objects.custom.write forms-uploaded-files settings.users.read crm.import contacts content reports social automation settings.billing.writ[...]"
      ]
    }
  ],
  "tags": []
}
